<?php $this->placeholder('Head')->captureStart() ?>
<title><?php echo DFL_NOME . ' - ' . ucfirst(Zend_Auth::getInstance()->getIdentity()->user_apelido) ?> - Configurar Senha</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link media="screen" rel="stylesheet" type="text/css" href="/temas/default/default/css/com-formulario.css" />
<script type="text/javascript" language="javascript" src="/scripts/alex/campo.js"></script>
<script type="text/javascript" language="javascript">
    function salvar(){
        erro = 0;
        f = document.formulario;
        if(f.user_senha_atual.value.length < 6){
            marcaCampoErro(f.user_senha_atual); erro++;
        }
        if(f.user_senha.value.length < 6){
            marcaCampoErro(f.user_senha); erro++;
        }
        if(f.user_senha_repitida.value.length < 6 || f.user_senha_repitida.value != f.user_senha.value){
            marcaCampoErro(f.user_senha_repitida); erro++;
        }
        if(erro == 0){
            f.submit();
        }
    }
</script>
<?php $this->placeholder('Head')->captureEnd() ?>

<div class="CONTEINER" style="background-image: url('/temas/default/default/fundos/fundoPainelIdCard.png');">
    <div class="TEXTO">
        <div class="p simples">
            Para alterar a senha você precisará inserir a atual e duas vezes a nova senha no
            formulário abaixo. Mas antes confira algumas de nossas recomendações para uma boa senha:
            
        </div>
        <div class="p simples">
            <ul>
                <li><b>-</b> Utilize uma senha diferente das que você já possui em outros luares;</li>
                <li><b>-</b> Crie senhas com mais de 6 caracteres;</li>
                <li><b>-</b> Misture letras números e símbolos em sua senha;</li>
                <li><b>-</b> Não utilize informações pessoais para criar uma senha; (Ex: Datas)</li>
                <li><b>-</b> Evite utilizar informações muito óbvias; (Ex: Nomes de coisas que gosta)</li>
                <li><b>-</b> Evite letras ou números em sequencia; (Ex: 123, abc ou aeiou)</li>
            </ul>
        </div>
    </div>
    <form class="FORMULARIO" name="formulario" action="/user/configurar-senha" method="post">
        <center>
            <table class="tabela">
                <tr><th>Senha atual
                        <div class="DICA-ICONE">
                            <div class="DICA">
                                <div class="corpo">
                                    <div class="topico">Campo obrigatório.</div>
                                    <div class="texto">Insira neste campo a senha que você esta utilizando atualmente.</div>
                                </div>
                                <div class="seta"></div>
                            </div>
                        </div>
                    </th>
                    <td><input class="Text" type="password" name="user_senha_atual" maxlength="20" autocomplete="off" onclick="desmarcaCampo(this)" ></td>
                </tr>

                <tr><th colspan="2" class="opcoes"></th></tr>
                <tr><th>Nova senha
                        <div class="DICA-ICONE">
                            <div class="DICA">
                                <div class="corpo">
                                    <div class="topico">Campo obrigatório.</div>
                                    <div class="texto">Crie uma senha para a sua conta. Tente seguir nossas recomendações. A senha deve ter ao menos 6 caracteres e misturar letras e números.</div>
                                </div>
                                <div class="seta"></div>
                            </div>
                        </div>
                    </th>
                    <td><input class="Text" type="password" name="user_senha" maxlength="20" autocomplete="off" onclick="desmarcaCampo(this)" ></td>
                </tr>
                <tr><th>Repita a nova senha
                        <div class="DICA-ICONE">
                            <div class="DICA">
                                <div class="corpo">
                                    <div class="topico">Campo obrigatório.</div>
                                    <div class="texto">Repita a nova senha informada no campo anterior.</div>
                                </div>
                                <div class="seta"></div>
                            </div>
                        </div>
                    </th>
                    <td><input class="Text" type="password" name="user_senha_repitida" maxlength="20" autocomplete="off" onclick="desmarcaCampo(this)" ></td>
                </tr>

                <tr><th class="opcoes" colspan="2">
                        <a class="alex-bt destaque verde-minimo" href="#" onclick="salvar()">Alterar</a>
                    </th>
                </tr>
            </table>
        </center>
    </form>
</div>

<?php
$this->placeholder('ConteudoEsquerda')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/user/_menu.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
?>