<?php $this->placeholder('Head')->captureStart() ?>
<title><?php echo DFL_NOME . ' - ' . ucfirst(Zend_Auth::getInstance()->getIdentity()->user_apelido) ?> - Fechar Conta</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link media="screen" rel="stylesheet" type="text/css" href="/temas/default/default/css/com-formulario.css" />
<script type="text/javascript" language="javascript" src="/scripts/alex/campo.js"></script>
<script type="text/javascript" language="javascript">
    function fechar(){
        if(document.formulario.user_senha.value.length < 6){
            marcaCampoErro(document.formulario.user_senha);
        }else{
            document.formulario.submit();
        }
    }
</script>
<?php $this->placeholder('Head')->captureEnd() ?>

<div class="CONTEINER" style="background-image: url('/temas/default/default/fundos/fundoPainelIdCard.png');">
    <div class="TEXTO">
        <div class="p simples">
            Para fechar a sua conta no <b><?php echo DFL_NOME ?></b> basta inserir sua senha no campo <b>"Senha"</b>
            e depois clicar no botão <b>"Fechar conta"</b>, ambos no final desta página. Mas antes de fazer
            isso você pode estar se perguntando algumas coisas sobre este processo.
        </div>
        <div class="topico">
            O que acontecerá com minha conta?
        </div>
        <div class="p simples">
            As contas no <?php echo DFL_NOME ?> não serão completamente excluídas serão apenas desativas, sendo assim
            você poderá reativá-la através do endereço de e-mail, que é a chave de identificação das contas.
        </div>

        <div class="topico">
            O que acontece com os meus dados pessoais?
        </div>
        <div class="p simples">
            O e-mail é a chave de identificação das contas, por isso ele não será removido. Todos os
            outros dados, tais como: Nome, Apelido, Senha, Data de Nascimento, Endereço e Etc., <b>serão
            excluídos permanentemente.</b>
        </div>

        <div class="topico">
            O que farão com o meu e-mail após eu fechar a conta?
        </div>
        <div class="p simples">
            Como dito, o e-mail não será removido, pois ele identifica a conta. Entretanto ele <b>NÃO</b>
            será utilizado para mais nada além disso. Não poderá ser negociado, divulgado ou compartilhado,
            nem com terceiros nem mesmo dentro do <?php echo DFL_NOME ?>. Servirá apenas para encontrar e reativar
            a sua conta caso você volte.
        </div>

        <div class="topico">
            O que acontece com o conteúdo que eu criei dentro do site?
        </div>
        <div class="p simples">
            Os conteúdos que você criou que possuírem relação com outros usuários, tais como:
            Perguntas; Respostas; Qualificações e Etc., são contribuições públicas e por
            isso não serão removidos. Estes conteúdos passarão a ser relacionados e mantidos pelo
            próprio site. Já os conteúdos de uso pessoal, tais
            como: Anotações, Favoritos, Marcações, Estatísticas e Etc., <b>serão excluídos
            permanentemente</b>.
        </div>

        <div class="topico">
            O que fazer para reativar minha conta?
        </div>
        <div class="p simples">
            Para reativar uma conta você precisará refazer o cadastro no <?php echo DFL_NOME ?>, utilizando
            o mesmo e-mail e incluindo novamente seus dados pessoais. Será enviada uma mensagem de
            confirmação para o e-mail cadastrado e após a confirmação você poderá utilizar sua conta,
            no entanto não será possível recuperar as informações excluídas no fechamento da conta.
        </div>
    </div>
    <form class="FORMULARIO" name="formulario" action="/user/fechar-conta" method="post">
        <center>
            <table class="tabela">
                <tr><th>Senha
                        <div class="DICA-ICONE">
                            <div class="DICA">
                                <div class="corpo">
                                    <div class="topico">Campo obrigatório.</div>
                                    <div class="texto">Insira neste campo a senha que você esta utilizando atualmente.</div>
                                </div>
                                <div class="seta"></div>
                            </div>
                        </div>
                    </th>
                    <td><input class="Text" type="password" name="user_senha" maxlength="20" autocomplete="off" onclick="desmarcaCampo(this)" ></td>
                </tr>

                <tr><th class="opcoes" colspan="2">
                        <a class="alex-bt destaque verde-minimo" href="#" onclick="fechar()">Fechar conta</a>
                    </th>
                </tr>
            </table>
        </center>
    </form>
</div>

<?php
$this->placeholder('ConteudoEsquerda')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/user/_menu.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
?>