<?php $this->placeholder('Head')->captureStart() ?>
<title><?php echo DFL_NOME . ' - ' . ucfirst(Zend_Auth::getInstance()->getIdentity()->user_apelido) ?></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<?php $this->placeholder('Head')->captureEnd() ?>

<div class="CONTEINER">
    <div class="TEXTO">
        <div class="topico">Página...</div>
        <div class="p">
            ... em contrução.
        </div>
    </div>
</div>

<?php
$this->placeholder('ConteudoEsquerda')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/user/_menu.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
?>