<?php $this->placeholder('Head')->captureStart() ?>
<title><?php echo DFL_NOME . ' - ' . ucfirst($this->obj['user_apelido']) ?></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<script type="text/javascript" language="javascript" src="/scripts/alex/campo.js"></script>
<script type="text/javascript" language="javascript">
    function marcarFiltro(obj){
        if(obj.name == 'palavra_chave'){
            if(obj.value.length > 0 && obj.value != 'palavra-chave...'){
                marcaCampoOk(obj);
                return;
            }
        }else{
            if(obj.value != 0){
                marcaCampoOk(obj);
                return;
            }
        }
        desmarcaCampo(obj);
    }
    function marcarFiltroAll(){
        marcarFiltro(document.getElementById('estado'));
        marcarFiltro(document.getElementById('partido'));
        marcarFiltro(document.getElementById('ano'));
        marcarFiltro(document.getElementById('tema'));
        marcarFiltro(document.getElementById('tipo'));
        marcarFiltro(document.getElementById('situacao'));
        marcarFiltro(document.getElementById('palavra_chave'));
    }
    function formSubmit(){
        link = '/user/projetos';
        palavra_chave = document.getElementById('palavra_chave');
        if(palavra_chave.value.length > 2 && palavra_chave.value != 'palavra-chave...'){
            link += '/palavra-chave/' + palavra_chave.value;
        }
        if(document.getElementById('ano').value > 0){
            link += '/ano/' + document.getElementById('ano').value;
        }
        if(document.getElementById('tema').value > 0){
            link += '/tema/' + document.getElementById('tema').value;
        }
        if(document.getElementById('tipo').value > 0){
            link += '/tipo/' + document.getElementById('tipo').value;
        }
        if(document.getElementById('situacao').value > 0){
            link += '/situacao/' + document.getElementById('situacao').value;
        }
        vaiPara(link);
    }
</script>
<?php $this->placeholder('Head')->captureEnd() ?>

<div class="CONTEINER">
    <div class="FILTRO">
        <select id="estado" class="item" onchange="marcarFiltro(this)" style="display: none">
        </select>
        <select id="partido" class="item" onchange="marcarFiltro(this)" style="display: none">
        </select>
        <select id="ano" class="item" onchange="marcarFiltro(this)" style="width: 120px">
            <option value="0" class="label">ANO</option>
            <?php
            for ($ano=date('Y'); $ano>=1988; $ano--) {
                echo '<option value="' . $ano . '"';
                if(isset($this->Lista['get']['ano']) && $this->Lista['get']['ano'] == $ano){
                    echo ' selected="selected"';
                }
                echo '>' . $ano . '</option>';
            }
            ?>
        </select>
        <select id="tema" class="item" onchange="marcarFiltro(this)" style="display: none">
            <option value="0" class="label">TEMA</option>
            <?php
            foreach (Zend_Registry::get('db')->fetchAll('SELECT * FROM pro_tema ORDER BY tema_nome') as $value) {
                echo '<option value="' . $value['tema_id'] . '"';
                if(isset($this->Lista['get']['tema']) && $this->Lista['get']['tema'] == $value['tema_id']){
                    echo ' selected="selected"';
                }
                echo '>' . $value['tema_nome'] . '</option>';
            }
            ?>
        </select>
        <select id="tipo" class="item" onchange="marcarFiltro(this)" style="width: 120px">
            <option value="0" class="label">TIPO</option>
            <?php
            foreach (Zend_Registry::get('db')->fetchAll('SELECT * FROM pro_tipo_lei ORDER BY tplei_nome') as $value) {
                echo '<option value="' . $value['tplei_id'] . '"';
                if(isset($this->Lista['get']['tipo']) && $this->Lista['get']['tipo'] == $value['tplei_id']){
                    echo ' selected="selected"';
                }
                echo '>' . $value['tplei_nome'] . '</option>';
            }
            ?>
        </select>
        <select id="situacao" class="item" onchange="marcarFiltro(this)" style="width: 120px">
            <option value="0" class="label">SITUAÇÃO</option>
            <?php
            foreach (Zend_Registry::get('db')->fetchAll('SELECT * FROM pro_situacao ORDER BY situacao_nome') as $value) {
                echo '<option value="' . $value['situacao_id'] . '"';
                if(isset($this->Lista['get']['situacao']) && $this->Lista['get']['situacao'] == $value['situacao_id']){
                    echo ' selected="selected"';
                }
                echo '>' . $value['situacao_nome'] . '</option>';
            }
            ?>
        </select>
        <input type="hidden" id="palavra_chave_atual" value="<?php if(isset($this->Lista['get']['palavra-chave'])) echo $this->Lista['get']['palavra-chave'] ?>">
        <input type="text" id="palavra_chave" name="palavra_chave" class="item text" value="<?php echo (isset($this->Lista['get']['palavra-chave']) && $this->Lista['get']['palavra-chave'] != '') ? ($this->Lista['get']['palavra-chave']) : ('palavra-chave...'); ?>" lang="palavra-chave..." maxlength="100" onfocus="entrou(this)" onblur="saiu(this);marcarFiltro(this);" onkeyup="marcarFiltro(this)" title="Palavra-chave para a busca.">
        <a class="item alex-bt" onclick="formSubmit()" ><img class="icone" src="/temas/default/default/icones/search.png" title="Buscar" title="Buscar" />Buscar</a>
        <a class="item alex-bt" href="/user/projetos" style="background-image: url('/temas/default/default/icones/remove.png')" title="Reiniciar Busca" ></a>
    </div>
    
    <?php
    if ($this->Lista['pagina']['qtd-itens'] > 0) {
        echo '</div><div class="RESULTADO" id="RESULTADO">';
        include APPLICATION_PATH . '/modules/default/views/scripts/projetos/ajax-paginacao.phtml';
    } else {
        echo '<div class="RESULTADO"><div class="mensagem"><i>NENHUM PROJETO FOI ENCONTRADO</i></div></div>';
    }
    ?>
</div>

<script type="text/javascript" language="javascript">
    var jQPaginaStatus = 0;
    var jQPaginaAtual = <?php echo $this->Lista['pagina']['atual'] ?>;
    var jQPaginaFinal = <?php echo $this->Lista['pagina']['fim'] ?>;
    
    $(window).bind("scroll", function(){
        page = $('#CONTEUDO').height() + 200;
        if(($(window).scrollTop() + $(window).height()) > page){
            if(jQPaginaStatus == 0 && jQPaginaAtual < jQPaginaFinal){
                jQPaginaStatus = 1;
                $.post('/projetos/ajax-paginacao/id/0', {
                    'pagina': ++jQPaginaAtual,
                    'usuario': <?php echo Zend_Auth::getInstance()->getIdentity()->user_id ?>,
                    'ano': <?php echo (isset($this->Lista['get']['ano']))?($this->Lista['get']['ano']):(0) ?>,
                    'tema': <?php echo (isset($this->Lista['get']['tema']))?($this->Lista['get']['tema']):(0) ?>,
                    'tipo': <?php echo (isset($this->Lista['get']['tipo']))?($this->Lista['get']['tipo']):(0) ?>,
                    'situacao': <?php echo (isset($this->Lista['get']['situacao']))?($this->Lista['get']['situacao']):(0) ?>,
                    'palavra-chave': document.getElementById('palavra_chave_atual').value
                }, function(data){
                    jQPaginaStatus = 0;
                    document.getElementById('RESULTADO').innerHTML += data.toString();
                }, 'html');
            }
        }
    });

    window.onload(marcarFiltroAll());
</script>

<?php
$this->placeholder('ConteudoEsquerda')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/user/_menu.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
?>