<style>
    body{
        font-family: fantasy;
        margin: 0;
        padding: 0;
    }
    table{
        width: 100%;
        text-align: left;
        margin: 0;
    }
    table tr{
    }
    table tr th{
        background: #000;
        padding: 3px 5px;
        color: #fff;
    }
    table tr td{
        padding: 3px 5px;
    }
    table tr td .cp{
        width: 90px;
        padding: 10px 5px;
        margin: -5px;
        border: none;
        background: none;
    }
    table tr td img{
        height: 20px;
    }
    table tr .foto{
        height: 100px;
        margin: -3px -5px -8px -5px;
    }
    table tr .cands{
        vertical-align: top;
        padding: 0
    }
    table tr td table{
        margin: 0;
        padding: 0;
    }
    table tr td table tr th{
        padding: 3px 5px;
        background: none;
        color: #888;
    }
    table tr:hover td{
        background: #efe;
    }
    .par{
       background: #fff; 
    }
    .impar{
       background: #eee; 
    }
</style>

<script>
    function atualizar(pessoa_id){
        if(confirm('ATUALIZAR ?')){
            for(c=0; c<document.forms.length; c++){
                if(document.forms[c].name == 'form'+pessoa_id){
                    document.forms[c].p_op.value = 'UPDATE';
                    document.forms[c].submit();
                }
            }
        }
    }
    function excluir(pessoa_id){
        if(confirm('EXCLUIR ?')){
            for(c=0; c<document.forms.length; c++){
                if(document.forms[c].name == 'form'+pessoa_id){
                    document.forms[c].p_op.value = 'DELETE';
                    document.forms[c].submit();
                }
            }
        }
    }
    function juntar(){
        if(confirm('JUNTAR ?')){
            document.formJoin.submit();
        }
    }
</script>

<?php
if(count($this->lista) > 0){
    ?>
    <table style="width: 2100px;">
        <tr><th width="65px">OPÇÕES</th>
            <th width="60px">FOTO</th>
            <th width="70px">ID</th>
            <th width="10px">TITULO</th>
            <th width="10px">CPF</th>
            <th width="10px">NASC</th>
            <th width="10px">APELIDO</th>
            <th width="10px">NOME</th>
            <th width="40px">NAC</th>
            <th width="40px">NAT</th>
            <th width="40px">OCU</th>
            <th width="40px">ESC</th>
            <th width="40px">CIV</th>
            <th>ELEICÕES</th>
        </tr>
    
        <?php
        $db = Zend_Registry::get('db');
        $anos = array();
        $data = $this->lista[0];
        $data['pessoa_nome'] = Alex_Util::trataNome($data['pessoa_nome']);
        $data['pessoa_apelido'] = Alex_Util::trataNome($data['pessoa_apelido']);
        $ufs = Default_Model_Lista_Estado::get();

        foreach ($this->lista as $key => $p) {
            echo '<form name="form' . $p['pessoa_id'] . '" action="" method="post"><input type="hidden" name="p_op" value="" />';
                echo '<tr class="' . (($key%2 == 0)?('par'):('impar')) . '" >';
                    echo '<td>';
                        echo '<input type="button" onclick="atualizar(' . $p['pessoa_id'] . ')" value="SALVAR" />';
                        echo '<input type="button" onclick="excluir(' . $p['pessoa_id'] . ')" value="EXCLUIR" />';
                    echo '</td>';
                    echo '<td><img class="foto" src="/uploads/pessoas' . Default_Model_Diretorio::getDiretorioPessoa($p['pessoa_id']) . '/foto.jpg" /></td>';
                    echo '<td><input class="cp" type="text" name="p_id" value="' . $p['pessoa_id'] . '" readonly /></td>';
                    echo '<td><input class="cp" type="text" name="p_te" value="' . $p['pessoa_titulo_eleitor'] . '" /></td>';
                    echo '<td><input class="cp" type="text" name="p_pf" value="' . $p['pessoa_cpf'] . '" /></td>';
                    echo '<td ' . (($data['pessoa_data_nascimento'] != $p['pessoa_data_nascimento'])?(' style="background:#ff0"'):('')) . '><input class="cp" type="text" name="p_dn" value="' . $p['pessoa_data_nascimento'] . '" /></td>';
                    echo '<td ' . (($data['pessoa_apelido'] != Alex_Util::trataNome($p['pessoa_apelido']))?(' style="background:#ff0"'):('')) . '><input class="cp" type="text" name="p_ap" value="' . $p['pessoa_apelido'] . '" style="width:300px" /></td>';
                    echo '<td ' . (($data['pessoa_nome'] != Alex_Util::trataNome($p['pessoa_nome']))?(' style="background:#ff0"'):('')) . '><input class="cp" type="text" name="p_nm" value="' . $p['pessoa_nome'] . '" style="width:300px" /></td>';
                    echo '<td>' . $p['pessoa_nacionalidade_id'] . '</td>';
                    echo '<td>' . $ufs[$p['pessoa_nat_estado_id']][0] . '</td>';
                    echo '<td>' . $p['pessoa_ocupacao_id'] . '</td>';
                    echo '<td>' . $p['pessoa_escolaridade_id'] . '</td>';
                    echo '<td>' . $p['pessoa_estado_civil_id'] . '</td>';
                    echo '<td class="cands">';
                        $candidaturas = $db->fetchAll('SELECT * FROM pu_candidatura C, pu_candidatura_detalhe D WHERE C.pessoa_id=' . $p['pessoa_id'] . ' && C.cand_id=D.cand_id');
                        if(count($candidaturas) > 0){
                            echo '<table>';
                                echo '<tr>';
                                echo '<th width="20px">ANO</th>';
                                echo '<th width="20px">UF</th>';
                                echo '<th width="70px">R$</th>';
                                echo '<th width="200px">CARGO</th>';
                                echo '<th>MUNICIPIO</th>';
                                echo '</tr>';
                                foreach ($candidaturas as $c) {
                                    echo '<tr>';
                                    if(isset($anos[$c['eleicao_id']])){
                                        echo '<td style="background:#ff0">' . $c['eleicao_id'] . '</td>';
                                    }else{
                                        $anos[$c['eleicao_id']] = '';
                                        echo '<td>' . $c['eleicao_id'] . '</td>';
                                    }
                                    echo '<td width="30px">' . $ufs[$c['cand_estado_id']][0] . '</td>';

                                    echo '<td>';
                                        $patri = $db->fetchRow('SELECT sum(bem_valor) AS total FROM pu_bem WHERE pessoa_id=' . $p['pessoa_id'] . ' && eleicao_id=' . $c['eleicao_id']);
                                        if(isset($patri) && $patri['total'] > 0){
                                            echo $patri['total'];
                                        }else{
                                            echo '0';
                                        }
                                    echo '</td>';
                                    echo '<td>' . Default_Model_Lista_Cargo::get($c['cargo_id']) . '</td>';
                                    echo '<td>' . $c['cand_municipio_id'] . '</td>';
                                    echo '</tr>';
                                }
                            echo '</table>';
                        }
                    echo '</td>';
                echo '</tr>';
            echo '</form>';
        }
    ?>
    </table>
    <?php
}
?>

<form name="formJoin" action="" method="post" style="padding:10px 5px;margin:0 2px">
    <input type="hidden" name="p_op" value="JOIN" />
    <input type="button" style="width:300px" onclick="<?php echo (count($this->lista) > 0)?('juntar()'):('')?>" value="JUNTAR TODOS {<?php echo count($this->lista) ?>}" />
    <input type="button" style="width:300px;float:right" onclick="document.location.href='/extracao/join/titulo'" value="TÍTULO DE ELEITOR" /><br/>
    <input type="button" style="width:300px;float:right" onclick="document.location.href='/extracao/join/cpf'" value="CPF" />
</form>

<?php
if(count($this->lista) > 0){
    Alex_Util::debugEscreve($data['pessoa_apelido'] . ' | ' . $data['pessoa_nome']);
}
Alex_Util::debugEscreve('JOINs REALIZADOS ATE AGORA: ' . $this->join);
?>