<div class="MINIATURA">
    <a class="foto" style="<?php echo (($this->obj['pessoa_flags'][4]==1)?('background-image: url(\'/dossies/ajax-foto/id/' . $this->obj['pessoa_id'] . '\');'):('')) ?>" href="/dossies/<?php echo $this->obj['pessoa_url'] ?>"></a>
    <div class="texto">
        <div class="nome"><?php echo $this->obj['pessoa_apelido'] ?></div>
        <div class="descricao"><?php echo $this->obj['pessoa_nome'] ?></div>
    </div>
    <div class="menu">
        <?php
        $action = explode('/', $_SERVER['REQUEST_URI'] . '/');
        $action = $action[3];
        ?>
        <a class="op <?php echo ($action == 'noticias')?('opAtivo'):('')?>" href="/dossies/<?php echo $this->obj['pessoa_url'] ?>/noticias" title="Projetos">Notícias<img src="/temas/default/default/icones/rss.png" /></a>
        <a class="op <?php echo ($action == 'projetos')?('opAtivo'):('')?>" href="/dossies/<?php echo $this->obj['pessoa_url'] ?>/projetos" title="Projetos">Projetos<img src="/temas/default/default/icones/page.png" /></a>
        <a class="op <?php echo ($action == 'patrimonios')?('opAtivo'):('')?>" href="/dossies/<?php echo $this->obj['pessoa_url'] ?>/patrimonios" title="Patrimônios">Patrimônios<img src="/temas/default/default/icones/pie_chart.png" /></a>
        <a class="op <?php echo ($action == 'candidaturas')?('opAtivo'):('')?>" href="/dossies/<?php echo $this->obj['pessoa_url'] ?>/candidaturas" title="Candidaturas">Candidaturas<img src="/temas/default/default/icones/id_card.png" /></a>
        <a class="op <?php echo ($action == 'dados')?('opAtivo'):('')?>" href="/dossies/<?php echo $this->obj['pessoa_url'] ?>/dados" title="Dados">Dados<img src="/temas/default/default/icones/user.png" /></a>
        <a class="op <?php echo ($action == 'links')?('opAtivo'):('')?>" href="/dossies/<?php echo $this->obj['pessoa_url'] ?>/links" title="Link's Relacionados">Link's Relacionados<img src="/temas/default/default/icones/add.png" /></a>
    </div>
</div>