<?php $this->placeholder('Head')->captureStart() ?>
<title>Link's Relacionados - <?php echo $this->obj['pessoa_nome'] . ' - Dossiês - ' . DFL_NOME ?></title>
<meta name="keywords" content="<?php echo $this->obj['pessoa_cpf'] . ', ' . $this->obj['pessoa_titulo_eleitor'] . ', ' . $this->obj['pessoa_nome'] ?>" />
<meta name="description" content="<?php echo $this->obj['pessoa_nome'] ?>" />
<link media="screen" rel="stylesheet" type="text/css" href="/temas/default/default/css/com-tabela.css" />
<?php $this->placeholder('Head')->captureEnd() ?>

<div class="CONTEINER" style="padding-bottom: 100px">
    <div class="TEXTO">
        <div class="topico">Saiba mais sobre <?php echo $this->obj['pessoa_nome'] ?>.</div>
        <div class="p">
            Utilize os dados deste político para saber ainda mais sobre sua vida pública fazendo consultas nos links abaixo.<br/>
        </div>
    </div>
    <center>
        <div class="TABELA" style="padding-bottom: 5px;min-width:400px;max-width:400px;width:400px">
            <?php
            if($this->obj['pessoa_cpf'] > 0){
                preg_match_all('/[0-9]{3}|[0-9]{2}/', str_pad($this->obj['pessoa_cpf'], 11, 0, STR_PAD_LEFT), $this->obj['pessoa_cpf']);
                $this->obj['pessoa_cpf'] = (count($this->obj['pessoa_cpf'] == 4))?(implode('.', $this->obj['pessoa_cpf'][0])):(' ');
            }else{
                $this->obj['pessoa_cpf'] = ' ';
            }
            if($this->obj['pessoa_titulo_eleitor'] > 0){
                preg_match_all('/[0-9]{3}+/', str_pad($this->obj['pessoa_titulo_eleitor'], 12, 0, STR_PAD_LEFT), $this->obj['pessoa_titulo_eleitor']);
                $this->obj['pessoa_titulo_eleitor'] = (count($this->obj['pessoa_titulo_eleitor'] == 4))?(implode('.', $this->obj['pessoa_titulo_eleitor'][0])):(' ');
            }else{
                $this->obj['pessoa_titulo_eleitor'] = ' ';
            }
            ?>
            <table class="tabela detalhe" style="min-width:392px;max-width:392px; margin-bottom: 20px;">
                <tr><th>Dados</th></tr>
                <tr><td><sub>Nome</sub><?php echo $this->obj['pessoa_nome'] ?></td></tr>
                <!--tr><td><sub>Data de Nascimento</sub><?php //echo $this->obj['pessoa_'] ?> </tr-->
                <!--tr><td><sub>RG</sub><?php //echo $this->obj['pessoa'] ?> </td></tr-->
                <tr><td><sub>CPF</sub><?php echo $this->obj['pessoa_cpf'] ?></td></tr>
                <!--tr><td><sub>Título de Eleitor</sub><?php echo $this->obj['pessoa_titulo_eleitor'] ?></td></tr-->
            </table>

            <table class="tabela detalhe" style="min-width:392px;max-width:392px">
                <tr><th>Link's</th></tr>
                <tr><td><sub>Receita Federal</sub><a href="http://www.receita.fazenda.gov.br/Aplicacoes/ATCTA/CPF/ConsultaPublica.asp">Validar CPF do Candidato</a></td></tr>
                <tr><td><sub>Receita Federal</sub><a href="http://www.receita.fazenda.gov.br/PessoaFisica/Restituicao/default.htm">Restituição do Imposto de Renda </a></td></tr>
                <tr><td><sub>Receita Federal</sub><a href="http://www.receita.fazenda.gov.br/Grupo2/Certidoes.htm">Certidão Negativa com a Previdência </a></td></tr>
                <tr><td><sub>Receita Federal</sub><a href="http://www.receita.fazenda.gov.br/Grupo2/Certidoes.htm">Tributos Federais e Dívida Ativa da União </a></td></tr>
                <tr><td><sub>Ministério da Fazenda</sub><a href="http://comprot.fazenda.gov.br/E-Gov/cons_generica_processos.asp">Pendência com o Fisco </a></td></tr>
            </table>
        </div>
    </center>
</div>


<?php
$this->placeholder('ConteudoEsquerda')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/dossies/_menu.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/sobre-nos/_menu.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
?>