<div class="MINIATURA">
    <a class="foto" style="<?php echo (($this->obj['user_icone']!='')?('background-image: url(\'' . $this->obj['user_icone'] . '\');'):('')) ?>" href="/perfis/<?php echo $this->obj['user_id'] ?>"></a>
    <div class="texto">
        <div class="nome"><?php echo $this->obj['user_apelido'] ?></div>
        <div class="descricao"><?php echo $this->obj['user_nome'] ?></div>
    </div>
    <div class="menu">
        <?php
        $action = explode('/', $_SERVER['REQUEST_URI'] . '/');
        $action = $action[3];
        ?>
        <a class="op <?php echo ($action == 'noticias')?('opAtivo'):('')?>" href="/perfis/<?php echo $this->obj['user_id'] ?>/noticias" title="Notícias">Notícias Adicionadas<img src="/temas/default/default/icones/rss.png" /></a>
        <a class="op <?php echo ($action == 'projetos')?('opAtivo'):('')?>" href="/perfis/<?php echo $this->obj['user_id'] ?>/projetos" title="Projetos">Projetos Votados<img src="/temas/default/default/icones/page.png" /></a>
        <!--a class="op <?php echo ($action == 'partidos')?('opAtivo'):('')?>" href="/perfis/<?php echo $this->obj['user_id'] ?>/partidos" title="Partidos">Partidos<img src="/temas/default/default/icones/page.png" /></a-->
        <!--a class="op <?php echo ($action == 'politicos')?('opAtivo'):('')?>" href="/perfis/<?php echo $this->obj['user_id'] ?>/politicos" title="Políticos">Políticos<img src="/temas/default/default/icones/page.png" /></a-->
    </div>
</div>