<?php
echo '<style>.TUDO .CONTEUDO .Caixa .SeparaEsquerda .ConteudoDireita{display: block}.TUDO .CONTEUDO .Caixa .SeparaEsquerda .SeparaDireita{margin-right: 248px}</style>';
include APPLICATION_PATH . '/modules/default/views/scripts/_projeto.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/_noticias.phtml';
//include APPLICATION_PATH . '/modules/default/views/scripts/_enquete.phtml';
?>