<?php
$nots = Zend_Registry::get('db')->fetchAll('
    SELECT * FROM not_noticia N, not_veiculo V
    WHERE N.noticia_veiculo_id=V.veiculo_id ' . ((Zend_Auth::getInstance()->hasIdentity())?('&& N.noticia_id NOT IN ( SELECT noticia_id FROM not_noticia_x_usuario WHERE user_id=' . Zend_Auth::getInstance()->getIdentity()->user_id . ' )'):('')) . '
    ORDER BY noticia_data_ini DESC LIMIT 0, 5
');
if(count($nots) > 0){
    //echo '<div class="CONTEINER"><div class="titulo tituloSozinho" style="background-image: url(\'/temas/default/default/icones/rss.png\');"><a href="/noticias">Notícias</a></div></div>';
    foreach ($nots as $obj) {
        echo '<div class="MINIATURA NOTICIA" id="miniaturaNoticia' . $obj['noticia_id'] . '">';
            if($obj['noticia_imagem'] != ''){
                echo '<div class="imagem" title="' . $obj['noticia_titulo'] . '"><img src="' . $obj['noticia_imagem'] . '" /></div>';
            }    
            echo '<div class="texto">';
                echo '<div class="nome"><a class="ajaxNoticiasLigar" target="_blank" noticia_id="' . $obj['noticia_id'] . '" href="' . $obj['noticia_link'] . '">' . $obj['noticia_titulo'] . '</a></div>';
                echo '<div class="descricao"><a class="ajaxNoticiasLigar" target="_blank" noticia_id="' . $obj['noticia_id'] . '" href="' . $obj['noticia_link'] . '">' . $obj['veiculo_link'] . '</a>' . (($obj['noticia_data'] != 0)?('<div class="topo">' . date('d/m/Y', $obj['noticia_data']) . '</div>'):('')) . '</div>';
                echo '<div class="descricao">' . $obj['noticia_resumo'] . '</div>';
            echo '</div>';
            echo '<div class="opcoes">';
                echo '<a href="/noticias/' . $obj['noticia_id'] . '" title="Detalhar" style="background-image: url(\'/temas/default/default/icones/zoom_in.png\')"></a>';
                echo '<div id="indiceNoticia' . $obj['noticia_id'] . '" style="float:right">';
                    echo '<a onclick="ajaxNoticiasImportancia(' . $obj['noticia_id'] . ', 1, this)" title="Mínima Importância" style="background-image: url(\'/temas/default/default/icones/star_gray.png\')"></a>';
                    echo '<a onclick="ajaxNoticiasImportancia(' . $obj['noticia_id'] . ', 2, this)" title="Baixa Importância" style="background-image: url(\'/temas/default/default/icones/star_gray.png\')"></a>';
                    echo '<a onclick="ajaxNoticiasImportancia(' . $obj['noticia_id'] . ', 3, this)" title="Importância Normal" style="background-image: url(\'/temas/default/default/icones/star_gray.png\')"></a>';
                    echo '<a onclick="ajaxNoticiasImportancia(' . $obj['noticia_id'] . ', 4, this)" title="Alta Importância" style="background-image: url(\'/temas/default/default/icones/star_gray.png\')"></a>';
                    echo '<a onclick="ajaxNoticiasImportancia(' . $obj['noticia_id'] . ', 5, this)" title="Máxima Importância" style="background-image: url(\'/temas/default/default/icones/star_gray.png\')"></a>';
                echo '</div>';
            echo '</div>';
        echo '</div>';
    }
}
?>