<?php
if($this->Lista['pagina']['fim'] >1){
    if($this->Lista['pagina']['fim'] > 9){
        echo '<a class="pagina" title="Primeira Página" href="' . $preLink . '/pagina/1" style="background-image: url(\'/temas/default/default/icones/navHome.png\');"> </a>';
    }
    echo '<a class="pagina" title="Página Anterior" href="' . $preLink . '/pagina/' . (($this->Lista['pagina']['atual'] > 1)?($this->Lista['pagina']['atual'] - 1):($this->Lista['pagina']['fim'])) . '" style="background-image: url(\'/temas/default/default/icones/navBack.png\');"> </a>';
    
    $ini = 1;
    $lad = 4;
    $qtd = (2 * $lad) + 1;
    if ($this->Lista['pagina']['fim'] > $qtd) {
        $ini = $this->Lista['pagina']['atual'] - $lad;
        if ($ini < 1) {
            $ini = 1;
        }
        if ($ini + $qtd - 1 > $this->Lista['pagina']['fim']) {
            $ini-=$ini + $qtd - 1 - $this->Lista['pagina']['fim'];
        }
    }
    
    for ($i = 0; $i < $qtd; $i++) {
        echo '<a class="pagina';
        if ($this->Lista['pagina']['atual'] == $ini) {
            echo ' atual"';
        }else{
            echo '" href="' . $preLink . '/pagina/' . $ini . '" ';
        }
        echo 'title="Página ' . $ini . '">' . $ini . '</a>';
        $ini++;
        if ($ini > $this->Lista['pagina']['fim']) {
            break;
        }
    }
    
    echo '<a class="pagina" title="Próxima Página" href="' . $preLink . (($this->Lista['pagina']['atual'] < $this->Lista['pagina']['fim'])?('/pagina/' . ($this->Lista['pagina']['atual'] + 1)):('')) . '" style="background-image: url(\'/temas/default/default/icones/navNext.png\');"> </a>';
    if($this->Lista['pagina']['fim'] > 9){
        echo '<a class="pagina" title="Última Página" href="' . $preLink . '/pagina/' . $this->Lista['pagina']['fim'] . '" style="background-image: url(\'/temas/default/default/icones/navEnd.png\');"> </a>';
    }
}else{
    echo '<a class="pagina atual" title="Página Única">1</a>';
}