<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="glyphicon glyphicon-user"></i><b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
        <li><a href="/area-usuario/perfil"><i class="glyphicon glyphicon-user"></i> Perfil</a></li>
        <li><a href="/area-usuario/calendario"><i class="glyphicon glyphicon-calendar"></i> Calendário</a></li>
        <li><a href="/area-usuario/mensagens"><i class="glyphicon glyphicon-envelope"></i> Mensagens<span class="badge badge-danger">3</span></a></li>
        <li><a href="/area-usuario/tarefas"><i class="glyphicon glyphicon-tasks"></i> Tarefas<span class="badge badge-success">7</span></a></li>
        <li><a href="/area-usuario/configuracoes"><i class="glyphicon glyphicon-cog"></i> Configurações</a></li>
        <li class="divider"></li>
        <li><a href="javascript:;" id="TELA-CHEIA"><i class="glyphicon glyphicon-fullscreen"></i> Tela Cheia</a></li>
        <li><a href="/area-restrita/sair"><i class="glyphicon glyphicon-log-in"></i> Sair</a></li>
    </ul>
</li>