<div class="social">
    <center>
        <div class="g-plusone" data-href="<?= SYS_SOCIAL_GP_PAGE ?>" data-size="tall" ></div>
        <div class="fb-like" data-href="<?= SYS_SOCIAL_FB_PAGE ?>" data-send="false" data-layout="box_count" data-show-faces="false" data-action="like"></div>
        <a class="twitter-share-button" href="https://twitter.com/share" data-url="<?= SYS_URL ?>" data-lang="en" data-text="Conheçam: <?=SYS_NOME?>" data-dnt="true" data-count="vertical"></a>
    </center>
</div>