<?php
$db = Zend_Registry::get('db');
$lstPess = $lstPart = array();
foreach ($this->Lista['resultado'] as $i => $obj) {
    $lstPart[$obj['cand_partido_id']] = $obj['cand_partido_id'];
    $lstPess[$obj['cand_pessoa_id']] = $obj['cand_pessoa_id'];
}
foreach ($db->fetchAll('SELECT * FROM pu_partido WHERE partido_id in (' . (implode(', ', $lstPart)) . ')') as $value) {
    $lstPart[$value['partido_id']] = $value;
}
foreach ($db->fetchAll('SELECT pessoa_id, pessoa_nome, pessoa_url, pessoa_flags FROM pu_pessoa WHERE pessoa_id in (' . (implode(', ', $lstPess)) . ')') as $value) {
    $lstPess[$value['pessoa_id']] = $value;
}
foreach ($this->Lista['resultado'] as $i => $obj) {
    echo '<div class="MINIATURA">';
        echo '<div class="nota" title="' . $lstPart[$obj['cand_partido_id']]['partido_nome'] . '"><div class="texto"><div class="faixa"></div>' . $lstPart[$obj['cand_partido_id']]['partido_sigla'] . '</div></div>';
        echo '<a class="foto" href="/dossies/' . $lstPess[$obj['cand_pessoa_id']]['pessoa_url'] . '" style="' . (($lstPess[$obj['cand_pessoa_id']]['pessoa_flags'][4]==1)?('background-image: url(\'/dossies/ajax-foto/id/' . $obj['cand_pessoa_id'] . '\');'):('')) . '"></a>';
        echo '<div class="obs"><div class="faixa"></div>' . $obj['cand_urna_numero'] . '</div>';
        echo '<div class="texto">';
            echo '<div class="nome">' . $obj['cand_urna_nome'] . '</div>';
            echo '<div class="descricao">' . $lstPess[$obj['cand_pessoa_id']]['pessoa_nome'] . '</div>';
        echo '</div>';
    echo '</div>';
}
?>