<?php $this->placeholder('Head')->captureStart() ?>
<title>Candidatos - <?php echo DFL_NOME ?></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<script type="text/javascript" language="javascript" src="/scripts/alex/campo.js"></script>
<script type="text/javascript" language="javascript">
    function marcarFiltro(obj){
        if(obj.name == 'palavra_chave' && obj.value.length > 0 && obj.value != 'palavra-chave...'){
            marcaCampoOk(obj);
            return;
        }else{
            if(obj.value > 0){
                marcaCampoOk(obj);
                return;
            }
        }
        desmarcaCampo(obj);
    }
    function formSubmit(){
        link = '<?php echo $this->cargo_caminho ?>';
        if(document.getElementById('eleicao').value > 0){
            link += '/' + document.getElementById('eleicao').value;
        }
        if(document.getElementById('partido').value > 0){
            link += '/partido/' + document.getElementById('partido').value;
        }
        palavra_chave = document.getElementById('palavra_chave');
        if(palavra_chave.value.length > 0 && palavra_chave.value != 'palavra-chave...'){
            link += '/palavra-chave/' + palavra_chave.value;
        }
        vaiPara(link);
    }
</script>
<?php $this->placeholder('Head')->captureEnd() ?>

<div class="CONTEINER">
    <div class="FILTRO">
        <select id="eleicao" class="item" onchange="marcarFiltro(this)" style="width: 70px">
            <?php
            $tpEleicoes = (($this->cargo_id == 11 || $this->cargo_id == 13)?('Eleições Municipais'):('Eleições Majoritárias'));
            foreach (Default_Model_Lista_Eleicao::get() as $key => $value) {
                if($tpEleicoes == $value){
                    echo '<option value="' . $key . '"';
                    if(isset($this->Lista['get']['eleicao']) && $this->Lista['get']['eleicao'] == $key){
                        echo ' selected="selected"';
                    }
                    echo '>' . $key . '</option>';
                }
            }
            ?>
        </select>
        <select id="partido" class="item" onchange="marcarFiltro(this)" style="width: 299px">
            <option value="0" class="label">Partidos</option>
            <?php
            $db = Zend_Registry::get('db');
            foreach ($db->fetchAll('SELECT * FROM pu_partido') as $value) {
                if($value['partido_id'] > 0){
                    echo '<option value="' . $value['partido_id'] . '"';
                    if(isset($this->Lista['get']['partido']) && $this->Lista['get']['partido'] == $value['partido_id']){
                        echo ' selected="selected"';
                    }
                    echo '>' . $value['partido_sigla'] . ' - ' . $value['partido_nome'] . '</option>';
                }
            }
            ?>
        </select>
        <input type="hidden" id="palavra_chave_atual" value="<?php if(isset($this->Lista['get']['palavra-chave'])) echo $this->Lista['get']['palavra-chave'] ?>">
        <input type="text" name="palavra_chave" id="palavra_chave" class="item text" value="<?php echo (isset($this->Lista['get']['palavra-chave']) && $this->Lista['get']['palavra-chave'] != '') ? ($this->Lista['get']['palavra-chave']) : ('palavra-chave...'); ?>" lang="palavra-chave..." maxlength="100" onfocus="entrou(this)" onblur="saiu(this);marcarFiltro(this);" onkeyup="marcarFiltro(this)" title="Palavra-chave para a busca.">
        <a class="item alex-bt" onclick="formSubmit()" ><img class="icone" src="/temas/default/default/icones/search.png" title="Buscar" />Buscar</a>
        <a class="item alex-bt" href="<?php echo $this->cargo_caminho ?>" style="background-image: url('/temas/default/default/icones/remove.png')" title="Reiniciar Busca" ></a>
    </div>
    
    <?php
    if ($this->Lista['pagina']['qtd-itens'] > 0) {
        echo '</div><div class="RESULTADO" id="RESULTADO">';
        include APPLICATION_PATH . '/modules/default/views/scripts/candidatos/ajax-paginacao.phtml';
    }else{
        echo '<div class="RESULTADO"><div class="mensagem"><i>NENHUM CANDIDATO FOI ENCONTRADO</i></div></div>';
    }
    ?>
</div>

<script type="text/javascript" language="javascript">
    var jQPaginaStatus = 0;
    var jQPaginaAtual = <?php echo $this->Lista['pagina']['atual'] ?>;
    var jQPaginaFinal = <?php echo $this->Lista['pagina']['fim'] ?>;
    
    $(window).bind("scroll", function(){
        page = $('#CONTEUDO').height() + 200;
        if(($(window).scrollTop() + $(window).height() + 500) > page){
            if(jQPaginaStatus == 0 && jQPaginaAtual < jQPaginaFinal){
                jQPaginaStatus = 1;
                $.post('/candidatos/ajax-paginacao/id/0', {
                    'pagina': ++jQPaginaAtual,
                    'cargo': <?php echo $this->cargo_id ?>,
                    'eleicao': <?php echo $this->Lista['get']['eleicao'] ?>,
                    'partido': <?php echo (isset($this->Lista['get']['partido']))?($this->Lista['get']['partido']):(0) ?>,
                    'palavra-chave': document.getElementById('palavra_chave_atual').value
                }, function(data){
                    jQPaginaStatus = 0;
                    document.getElementById('RESULTADO').innerHTML += data.toString();
                }, 'html');
            }
        }
    });

    window.onload(marcarFiltro(document.getElementById('palavra_chave')));
</script>

<?php
$this->placeholder('ConteudoEsquerda')->captureStart();
//include APPLICATION_PATH . '/modules/default/views/scripts/candidatos/_menu.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/_projeto.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/_noticias.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/sobre-nos/_menu.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
?>