<?php $this->placeholder('Head')->captureStart() ?>
<title><?php echo DFL_NOME ?> jamais será vencido !</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<?php $this->placeholder('Head')->captureEnd() ?>

<div class="CONTEINER">
    <div style="padding: 10px 10px 7px 10px">
        <iframe width="715" height="536" src="//www.youtube.com/embed/7ip5rPMp2js" frameborder="0" allowfullscreen></iframe>
    </div>
</div>

<?php
$this->placeholder('ConteudoEsquerda')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/sobre-nos/_menu.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
?>