<? $this->placeholder('head')->captureStart() ?>
<title><?= SYS_NOME ?> jamais será vencido !</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<? $this->placeholder('head')->captureEnd() ?>

<h2>INDEX</h2>
<h3>Alô mundo!!!</h3>

<? $this->placeholder('script')->captureStart() ?>
<script type="text/javascript">
</script>
<? $this->placeholder('script')->captureEnd() ?>