<?php
$db = Zend_Registry::get('db');

$user = array();
if(Zend_Auth::getInstance()->hasIdentity()){
    foreach ($db->fetchAll('
        SELECT projeto_id, user_participacao_id
        FROM pro_projeto_x_usuario
        WHERE user_id=' . Zend_Auth::getInstance()->getIdentity()->user_id . '
           && projeto_id=' . $this->obj['projeto_id'] . '
           && user_participacao_id IN (1,2)
    ') as $value) {
        $user[$value['projeto_id']] = $value['user_participacao_id'];
    }
}
?>

<div class="MINIATURA PROJETO">
    <div class="apelido" title="Código Local............: <?php echo $this->obj['projeto_id'] . '&#13;Código na Câmara..: ' . $this->obj['projeto_cd_origem'] ?>"><?php echo $this->obj['projeto_nome'] ?></div>
    <div class="estatistica" id="estatisticaProjeto<?php echo $this->obj['projeto_id'] ?>">
        <div class="votacao" title="Votos SIM....: <?php echo $this->obj['projeto_qtd_positivos'] . '&#13;Votos NÃO..: ' . $this->obj['projeto_qtd_negativos'] ?>">
            <div class="barra">
                <?php
                $total = $this->obj['projeto_qtd_positivos']+$this->obj['projeto_qtd_negativos'];
                if($total>0){
                    $s = (100*$this->obj['projeto_qtd_positivos'])/$total;
                    $n = (100*$this->obj['projeto_qtd_negativos'])/$total;
                    if($this->obj['projeto_qtd_positivos']>=$this->obj['projeto_qtd_negativos']){
                        echo '<div class="sim" style="width: '.$s.'%"><div class="indice">' . ceil($s) . '%</div></div><div class="nao" style="width: '.$n.'%"></div>';
                    }else{
                        echo '<div class="sim" style="width: '.$s.'%"></div><div class="nao" style="width: '.$n.'%"><div class="indice">' . ceil($n) . '%</div></div>';
                    }
                }else{
                    echo '<div class="indice">0%</div>';
                }
                ?>
            </div>
        </div>
    </div>

    <div class="texto">
        <div class="nome">Autor</div>
        <div class="descricao"><?php echo '<i>' . mb_strtoupper(substr($this->obj['projeto_autor'], 0, strpos($this->obj['projeto_autor'], '|'))) . '</i> ' ?></div>
    </div>
    <div class="texto">
        <div class="nome">Data de Apresentação</div>
        <div class="descricao"><?php echo '<i>' . date('d-m-Y', $this->obj['projeto_data_apresentacao']) . '</i>' ?></div>
    </div>
    <div class="texto">
        <div class="nome">Tipo de Lei</div>
        <div class="descricao"><?php echo '<div title="' . $this->obj['tplei_descricao'] . '"><i>' . $this->obj['tplei_sigla'] . ', ' . $this->obj['tplei_nome'] . '</i></div>' ?></div>
    </div>
    <div class="texto">
        <div class="nome">Regime</div>
        <div class="descricao"><?php echo '<div title="' . $this->obj['regime_descricao'] . '"><i>' . $this->obj['regime_nome'] . '</i></div>' ?></div>
    </div>
    <div class="texto">
        <div class="nome">Situação</div>
        <div class="descricao"><?php echo '<div title="' . $this->obj['situacao_descricao'] . '"><i>' . $this->obj['situacao_nome'] . '</i></div>' ?></div>
    </div>
    <div class="texto">
        <div class="nome">Apreciação</div>
        <div class="descricao"><?php echo '<div title="' . $this->obj['apreciacao_descricao'] . '"><i>' . $this->obj['apreciacao_nome'] . '</i></div>' ?></div>
    </div>
    <div class="texto">
        <div class="nome">Proposta Completo do Projeto</div>
        <div class="descricao"><i><b><?php echo ($this->obj['projeto_link_inteiro_teor']!='')?('<a target="_blank" href="' . $this->obj['projeto_link_inteiro_teor'] . '" title="Aqui você encontrará a proposta original apresentada.">Download</a>'):('Não Informado')?></b></i></div>
    </div>

    <div class="urna">
        <div class="botoes<?php echo ((isset($user[$this->obj['projeto_id']]))?(($user[$this->obj['projeto_id']]==1)?(' votouSim'):(' votouNao')):('')) . '" id="urnaProjeto' . $this->obj['projeto_id'] ?>"><div>
            <div><a class="sim" onclick="ajaxProjetosVotarSim(<?php echo $this->obj['projeto_id'] ?>)" title="Votar SIM">SIM</a></div>
            <div><a class="nao" onclick="ajaxProjetosVotarNao(<?php echo $this->obj['projeto_id'] ?>)" title="Votar NÃO">NÃO</a></div>
        </div></div>
    </div>

    <div class="opcoes">
        <a href="/projetos" title="Voltar Para os Projetos" style="background-image: url('/temas/default/default/icones/back.png')"></a>
    </div>
</div>