<?php
$db = Zend_Registry::get('db');

$projetos = array();
foreach ($this->Lista['resultado'] as $obj) {
    $projetos[] = $obj['projeto_id'];
}

$user = array();
if(Zend_Auth::getInstance()->hasIdentity() && count($projetos) > 0){
    foreach ($db->fetchAll('
        SELECT projeto_id, user_participacao_id
        FROM pro_projeto_x_usuario
        WHERE user_id=' . Zend_Auth::getInstance()->getIdentity()->user_id . '
           && projeto_id IN (' . implode(', ', $projetos) . ')
           && user_participacao_id IN (1,2)
    ') as $value) {
        $user[$value['projeto_id']] = $value['user_participacao_id'];
    }
}

foreach ($this->Lista['resultado'] as $obj) {
    echo '<div class="MINIATURA PROJETO">';
        echo '<a class="apelido" href="/projetos/' . $obj['projeto_url'] . '"  title="Nome.............: ' . $obj['projeto_nome'] . '&#13;Apresentação: ' . date('d-m-Y', $obj['projeto_data_apresentacao']) . '&#13;Tipo................: ' . $obj['tplei_nome'] . '&#13;Situação.........: ' . $obj['situacao_nome'] . '">' . $obj['projeto_nome'] . '</a>';
        if(isset($obj['pessoa_id'])){
            echo '<div class="apelido" title="ESTE É O VOTO DESTE POLÍTICO" style="text-align:center">';
                if($obj['pessoa_participacao_id'] == 0){
                    echo '-';
                }elseif($obj['pessoa_participacao_id'] == 1){
                    echo 'VOTOU SIM';
                }elseif($obj['pessoa_participacao_id'] == 2){
                    echo 'VOTOU NÃO';
                }else{
                    echo 'NÃO VOTOU';
                }
            echo '</div>';
        }elseif(isset($obj['partido_id'])){
            echo '<div class="apelido" title="ESTE É O VOTO DESTE PARTIDO" style="text-align:center">';
                if($obj['partido_participacao_id'] == 0){
                    echo '-';
                }elseif($obj['partido_participacao_id'] == 1){
                    echo 'VOTOU SIM';
                }elseif($obj['partido_participacao_id'] == 2){
                    echo 'VOTOU NÃO';
                }else{
                    echo 'NÃO VOTOU';
                }
            echo '</div>';
        }elseif(isset($obj['user_id'])){
            echo '<div class="apelido" title="ESTE É O VOTO DESTE USUÁRIO" style="text-align:center">';
                if($obj['user_participacao_id'] == 1){
                    echo 'VOTOU SIM';
                }elseif($obj['user_participacao_id'] == 2){
                    echo 'VOTOU NÃO';
                }else{
                    echo 'VOTOU INEXISTENTE';
                }
            echo '</div>';
        }

        echo '<div class="estatistica" id="estatisticaProjeto' . $obj['projeto_id'] . '">';
            echo '<div class="votacao" title="Votos SIM....: ' . $obj['projeto_qtd_positivos'] . '&#13;Votos NÃO..: ' . $obj['projeto_qtd_negativos'] . '">';
                echo '<div class="barra">';
                    $total = $obj['projeto_qtd_positivos']+$obj['projeto_qtd_negativos'];
                    if($total>0){
                        $s = (100*$obj['projeto_qtd_positivos'])/$total;
                        $n = (100*$obj['projeto_qtd_negativos'])/$total;
                        if($obj['projeto_qtd_positivos']>=$obj['projeto_qtd_negativos']){
                            echo '<div class="sim" style="width: '.$s.'%"><div class="indice">' . ceil($s) . '%</div></div><div class="nao" style="width: '.$n.'%"></div>';
                        }else{
                            echo '<div class="sim" style="width: '.$s.'%"></div><div class="nao" style="width: '.$n.'%"><div class="indice">' . ceil($n) . '%</div></div>';
                        }
                    }else{
                        echo '<div class="indice">0%</div>';
                    }
                echo '</div>';
            echo '</div>';
        echo '</div>';
        
        echo '<div class="texto">';
            if($obj['projeto_descricao']!=''){
                echo '<div class="nome">Descrição</div>';
                echo '<div class="descricao scroll" onmouseout="$(this).animate({scrollTop: 0}, 400);">' . $obj['projeto_descricao'] . '</div>';
            }else{
                echo '<div class="nome">Ementa</div>';
                echo '<div class="descricao scroll" onmouseout="$(this).animate({scrollTop: 0}, 400);">' . $obj['projeto_ementa'] . '</div>';
            }
        echo '</div>';
        
        echo '<div class="urna">';
            echo '<div class="ps"><a href="/projetos/' . $obj['projeto_url'] . '">SAIBA MAIS ANTES TE VOTAR</a></div>';
            echo '<div class="botoes' . ((isset($user[$obj['projeto_id']]))?(($user[$obj['projeto_id']]==1)?(' votouSim'):(' votouNao')):('')) . '" id="urnaProjeto' . $obj['projeto_id'] . '"><div>';
                echo '<div><a class="sim" onclick="ajaxProjetosVotarSim(' . $obj['projeto_id'] . ')" title="Votar SIM">SIM</a></div>';
                echo '<div><a class="nao" onclick="ajaxProjetosVotarNao(' . $obj['projeto_id'] . ')" title="Votar NÃO">NÃO</a></div>';
            echo '</div></div>';
        echo '</div>';
        
        echo '<div class="opcoes">';
            echo '<a href="/projetos/' . $obj['projeto_url'] . '" title="Detalhar Projeto" style="background-image: url(\'/temas/default/default/icones/zoom_in.png\');"></a>';
            //echo '<a href="" title="" style="background-image: url(\'/temas/default/default/icones/map_blue.png\');"></a>';
            //echo '<a href="" title="" style="background-image: url(\'/temas/default/default/icones/email.png\');"></a>';
            //echo '<a href="" title="" style="background-image: url(\'/temas/default/default/icones/pie_chart.png\');"></a>';
            //echo '<a href="" title="" style="background-image: url(\'/temas/default/default/icones/comment.png\');"></a>';
            //echo '<a href="" title="" style="background-image: url(\'/temas/default/default/icones/megaphone.png\');"></a>';
        echo '</div>';
    echo '</div>';
}
?>