<?php
echo '<div class="votacao" title="Votos SIM....: ' . $this->obj['projeto_qtd_positivos'] . '&#13;Votos NÃO..: ' . $this->obj['projeto_qtd_negativos'] . '">';
    echo '<div class="barra">';
        $total = $this->obj['projeto_qtd_positivos']+$this->obj['projeto_qtd_negativos'];
        if($total>0){
            $s = (100*$this->obj['projeto_qtd_positivos'])/$total;
            $n = (100*$this->obj['projeto_qtd_negativos'])/$total;
            if($this->obj['projeto_qtd_positivos']>=$this->obj['projeto_qtd_negativos']){
                echo '<div class="sim" style="width: '.$s.'%"><div class="indice">' . ceil($s) . '%</div></div><div class="nao" style="width: '.$n.'%"></div>';
            }else{
                echo '<div class="sim" style="width: '.$s.'%"></div><div class="nao" style="width: '.$n.'%"><div class="indice">' . ceil($n) . '%</div></div>';
            }
        }else{
            echo '<div class="indice">0%</div>';
        }
    echo '</div>';
echo '</div>';
?>