<?php $this->placeholder('Head')->captureStart() ?>
<title><?php echo DFL_NOME ?> - Cadastre-se</title>
<meta name="keywords" content="cadastro de usuários, usuário" />
<meta name="description" content="Utilize este formulário para fazer o seu cadastro no site." />
<link media="screen" rel="stylesheet" type="text/css" href="/temas/default/default/css/com-formulario.css" />
<script type="text/javascript" language="javascript" src="/scripts/alex/campo.js"></script>
<script type="text/javascript" language="javascript" src="/scripts/alex/filtro.js"></script>
<script type="text/javascript" language="javascript">
    function salvar(){
        return;
        erro = 0;
        f = document.formulario;
        if(f.user_nome.value.length < 2){
            marcaCampoErro(f.user_nome); erro++;
        }
        if(!(f.user_data_dia.value > 0)){
            marcaCampoErro(f.user_data_dia); erro++;
        }
        if(!(f.user_data_mes.value > 0)){
            marcaCampoErro(f.user_data_mes); erro++;
        }
        if(!(f.user_data_ano.value > 0)){
            marcaCampoErro(f.user_data_ano); erro++;
        }
        if(!(f.user_sexo_id.value > 0)){
            marcaCampoErro(f.user_sexo_id); erro++;
        }
        f.user_email.value = f.user_email.value.toLowerCase();
        if(f.user_email.value.length < 5 || !eEmailValido(f.user_email.value)){
            marcaCampoErro(f.user_email); erro++;
        }
        qtdNum = f.user_senha.value.replace(/\D/g, '').length;
        if(f.user_senha.value.length < 6 || qtdNum < 1 || (f.user_senha.value.length - qtdNum) < 1){
            marcaCampoErro(f.user_senha); erro++;
        }
        if(f.user_senha_repitida.value.length < 6 || f.user_senha_repitida.value != f.user_senha.value){
            marcaCampoErro(f.user_senha_repitida); erro++;
        }
        if(erro == 0){
            if(f.termos.checked){
                f.user_data_nascimento.value = f.user_data_ano.value+'-'+f.user_data_mes.value+'-'+f.user_data_dia.value;
                //f.submit();
            }else{
                alert('Para cadastrar-se você precisa aceitar nossos Termos e Políticas.');
            }
        }
    }
</script>
<?php $this->placeholder('Head')->captureEnd() ?>

<div class="CONTEINER" style="background-image: url('/temas/default/default/fundos/fundoPainelIdCard.png');">
    <div class="TEXTO">
        <div class="p simples">
            Os usuários cadastrados poderão influenciar o futuro de seu país, o cadastro é gratuito
            e você precisa apenas preencher o formulário abaixo.
        </div>
    </div>
    <form class="FORMULARIO" name="formulario" action="/area-restrita/cadastre-se" method="post">
        <center>
            <table>
                <tr><th>Nome
                        <div class="DICA-ICONE">
                            <div class="DICA">
                                <div class="corpo">
                                    <div class="topico">Campo obrigatório.</div>
                                    <div class="texto">Escreva neste campo o seu nome completo.</div>
                                    <div class="topico">Ex: Frederico O. Barreto.</div>
                                </div>
                                <div class="seta"></div>
                            </div>
                        </div>
                    </th>
                    <td><input disabled onclick="desmarcaCampo(this)" onkeypress="desmarcaCampo(this)" value="<?php echo $this->obj['user_nome'] ?>" name="user_nome" maxlength="200" autocomplete="off" type="text" class="Text" ></td>
                </tr>
                <tr><th>Data de Nascimento
                        <div class="DICA-ICONE">
                            <div class="DICA">
                                <div class="corpo">
                                    <div class="topico">Campo obrigatório.</div>
                                    <div class="texto">Escreva neste campo a sua data de nascimento.</div>
                                    <div class="topico">Ex: 17/11/1989.</div>
                                </div>
                                <div class="seta"></div>
                            </div>
                        </div>
                    </th>
                    <td><input disabled name="user_data_nascimento" autocomplete="off" type="hidden" readonly >
                        <select disabled onclick="desmarcaCampo(this)" name="user_data_dia" style="width: 100px">
                            <option value="0"></option>
                            <?php
                            if(isset($this->obj['user_data_nascimento']) && strlen($this->obj['user_data_nascimento']) == 10){
                                $dataParts = explode('-', $this->obj['user_data_nascimento']);
                            }else{
                                $dataParts = array('', '', '');
                            }
                            for($i=1; $i<32; $i++) {
                                echo '<option value="' . $i . '"';
                                if($i == $dataParts[2]){
                                    echo ' selected';
                                }
                                echo '>' . $i . '</option>';
                            }
                            ?>
                        </select>
                        <select disabled onclick="desmarcaCampo(this)" name="user_data_mes" style="width: 164px">
                            <option value="0"></option>
                            <?php
                            for($i=1; $i<13; $i++) {
                                echo '<option value="' . $i . '"';
                                if($i == $dataParts[1]){
                                    echo ' selected';
                                }
                                echo '>' . Alex_Util::mes($i) . '</option>';
                            }
                            ?>
                        </select>
                        <select disabled onclick="desmarcaCampo(this)" name="user_data_ano" style="width: 100px">
                            <option value="0"></option>
                            <?php
                            for($i=date('Y'); $i>date('Y')-130; $i--) {
                                echo '<option value="' . $i . '"';
                                if($i == $dataParts[0]){
                                    echo ' selected';
                                }
                                echo '>' . $i . '</option>';
                            }
                            ?>
                        </select>
                    </td>
                </tr>
                <tr><th>Sexo
                        <div class="DICA-ICONE">
                            <div class="DICA">
                                <div class="corpo">
                                    <div class="topico">Campo obrigatório.</div>
                                    <div class="texto">Selecione o seu sexo.</div>
                                </div>
                                <div class="seta"></div>
                            </div>
                        </div>
                    </th>
                    <td><select disabled onclick="desmarcaCampo(this)" name="user_sexo_id" >
                            <option value="0"></option>
                            <?php
                            foreach (Default_Model_Lista_Sexo::get() as $key => $value) {
                                echo '<option value="' . $key . '"';
                                if($key == $this->obj['user_sexo_id']){
                                    echo ' selected';
                                }
                                echo '>' . $value . '</option>';
                            }
                            ?>
                        </select></td>
                </tr>

                <tr><th colspan="2" class="opcoes"></th></tr>
                <tr><th>E-mail
                        <div class="DICA-ICONE">
                            <div class="DICA">
                                <div class="corpo">
                                    <div class="topico">Campo obrigatório.</div>
                                    <div class="texto">Escreva neste campo o seu endereço de e-mail para contato. Este endereço será utilizado para confirmar seu cadastro e para autenticar o seu acesso ao site.</div>
                                    <div class="topico">Ex: frederico.oc@dominio.com.</div>
                                </div>
                                <div class="seta"></div>
                            </div>
                        </div>
                    </th>
                    <td><input disabled onclick="desmarcaCampo(this)" onkeypress="desmarcaCampo(this);mascara(this, soEmail);" value="<?php echo $this->obj['user_email'] ?>" name="user_email" maxlength="100" autocomplete="off" type="text" class="Text" ></td>
                </tr>
                <tr><th>Senha
                        <div class="DICA-ICONE">
                            <div class="DICA">
                                <div class="corpo">
                                    <div class="topico">Campo obrigatório.</div>
                                    <div class="texto">Escreva neste campo a senha que você deseja utilizar para acesso ao site. Não seja tão óbvio utilizando dados pessoais. A senha deve ter ao menos 6 caracteres e misturar letras e números.</div>
                                </div>
                                <div class="seta"></div>
                            </div>
                        </div>
                    </th>
                    <td><input disabled onclick="desmarcaCampo(this)" onkeypress="desmarcaCampo(this)" name="user_senha" maxlength="20" autocomplete="off" type="password" class="Text" ></td>
                </tr>
                <tr><th>Repita a senha
                        <div class="DICA-ICONE">
                            <div class="DICA">
                                <div class="corpo">
                                    <div class="topico">Campo obrigatório.</div>
                                    <div class="texto">Escreva neste campo a mesma senha que você escreveu no campo anterior.</div>
                                </div>
                                <div class="seta"></div>
                            </div>
                        </div>
                    </th>
                    <td><input disabled onclick="desmarcaCampo(this)" onkeypress="desmarcaCampo(this)" name="user_senha_repitida" maxlength="20" autocomplete="off" type="password" class="Text" ></td>
                </tr>

                <tr><th class="opcoes"></th>
                    <th class="opcoes" style="text-align: left; color: #000">
                        <input disabled type="checkbox" name="termos" style="vertical-align: top" ><i style="display: inline-block; padding: 2px 0 0 2px;"> Li e aceito as <a href="/sobre-nos/politicas-e-termos" style="text-decoration: underline">políticas e termos</a> do site.</i>
                    </th>
                </tr>
                <tr><td class="opcoes" colspan="2">
                        <a class="alex-bt destaque verde-minimo" href="#" onclick="salvar()">Cadastrar</a>
                        <a class="alex-bt" href="#" onclick="document.formulario.reset()">Limpar</a>
                    </td>
                </tr>
            </table>
        </center>
    </form>
</div>

<?php
$this->placeholder('ConteudoEsquerda')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/sobre-nos/_menu.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
?>