<?php $this->placeholder('Head')->captureStart() ?>
<title><?php echo DFL_NOME ?> - Esqueci a senha</title>
<meta name="keywords" content="esquici a senha, nova senha" />
<meta name="description" content="Utilize este formulário para solicitar uma nova senha caso você não consiga se lembrar na sua senha." />
<link media="screen" rel="stylesheet" type="text/css" href="/temas/default/default/css/com-formulario.css" />
<script type="text/javascript" language="javascript" src="/scripts/alex/campo.js"></script>
<script type="text/javascript" language="javascript" src="/scripts/alex/filtro.js"></script>
<script type="text/javascript" language="javascript">
    function salvar(){
        f = document.formulario;
        f.user_email.value = f.user_email.value.toLowerCase();
        if(!eEmailValido(f.user_email.value)){
            marcaCampoErro(f.user_email);
        }else{
            f.submit();
        }
    }
</script>
<?php $this->placeholder('Head')->captureEnd() ?>

<div class="CONTEINER" style="background-image: url('/temas/default/default/fundos/fundoPainelIdCard.png');">
    <div class="TEXTO">
        <div class="p">
            Se você esqueceu sua senha de acesso à área restrita, poderá utilizar o formulário
            abaixo para fazer uma solicitação de nova senha. Para isso será necessário que você
            informe o e-mail que você utilizou no momento em que se cadastrou. Uma mensagem será
            enviada para este e-mail, com um link de confirmação, e após você confirmar, outra
            mensagem será enviada contendo uma nova senha, que deverá ser alterada o mais rápido
            possível.
        </div>
    </div>
    <form class="FORMULARIO" name="formulario" action="/area-restrita/esqueci-senha" method="post">
        <center>
            <table>
                <tr><th>E-mail
                        <div class="DICA-ICONE">
                            <div class="DICA">
                                <div class="corpo">
                                    <div class="topico">Campo obrigatório.</div>
                                    <div class="texto">Escreva neste campo o endereço de e-mail que você utilizou no momento do cadastro.</div>
                                </div>
                                <div class="seta"></div>
                            </div>
                        </div>
                    </th>
                    <td><input onclick="desmarcaCampo(this)" onkeypress="desmarcaCampo(this);mascara(this, soEmail)" name="user_email" maxlength="100" autocomplete="off" type="text" class="Text" ></td>
                </tr>

                <tr><td class="opcoes" colspan="2">
                        <a class="alex-bt destaque verde-minimo" href="#" onclick="salvar()">Solicitar nova senha</a>
                        <a class="alex-bt" href="#" onclick="document.formulario.reset()">Limpar</a>
                    </td>
                </tr>
            </table>
        </center>
    </form>
</div>

<?php
$this->placeholder('ConteudoEsquerda')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/sobre-nos/_menu.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
?>