<?php $this->placeholder('Head')->captureStart() ?>
<title><?php echo DFL_NOME ?> - Login</title>
<meta name="keywords" content="login, área restrita" />
<meta name="description" content="Utilize este formulário para se autenticar e começar a participar." />
<link media="screen" rel="stylesheet" type="text/css" href="/temas/default/default/css/com-formulario.css" />
<script type="text/javascript" language="javascript" src="/scripts/alex/campo.js"></script>
<script type="text/javascript" language="javascript" src="/scripts/alex/filtro.js"></script>
<script type="text/javascript" language="javascript">
    function entrar(){
        erro = 0;
        f = document.formulario;
        f.user_email.value = f.user_email.value.toLowerCase();
        if(!eEmailValido(f.user_email.value)){
            marcaCampoErro(f.user_email); erro++;
        }
        if(f.user_senha.value.length < 6){
            marcaCampoErro(f.user_senha); erro++;
        }
        if(erro == 0){
            f.submit();
        }
    }
</script>
<?php $this->placeholder('Head')->captureEnd() ?>

<div class="CONTEINER">
    <div class="TEXTO">
        <div class="topico">Autenticação</div>
        <div class="p">
            Este é o formulário para autenticação de usuários cadastrados.
            Caso você ainda não seja cadastrado, <b><a href="/area-restrita/cadastre-se">clique aqui</a></b>
            para se cadastrar gratuitamente.
        </div>
    </div>
    
    <form class="FORMULARIO" name="formulario" action="/area-restrita/entrar" method="post">
        <center>
            <table>
                <tr><th>E-mail
                        <div class="DICA-ICONE">
                            <div class="DICA">
                                <div class="corpo">
                                    <div class="topico">Campo obrigatório.</div>
                                    <div class="texto">Escreva neste campo o endereço de e-mail que você utilizou no momento do cadastro.</div>
                                </div>
                                <div class="seta"></div>
                            </div>
                        </div>
                    </th>
                    <td><input onclick="desmarcaCampo(this)" onkeypress="desmarcaCampo(this);mascara(this, soEmail);" name="user_email" type="text" class="Text"></td>
                </tr>
                <tr><th>Senha
                        <div class="DICA-ICONE">
                            <div class="DICA">
                                <div class="corpo">
                                    <div class="topico">Campo obrigatório.</div>
                                    <div class="texto">Escreva neste campo a senha que você utilizou no momento do cadastro.</div>
                                </div>
                                <div class="seta"></div>
                            </div>
                        </div>
                    </th>
                    <td><input onclick="desmarcaCampo(this)" onkeypress="desmarcaCampo(this)" name="user_senha" autocomplete="off" type="password" class="Text"></td>
                </tr>

                <tr><td class="opcoes" colspan="2">
                        <div style="float: right; width: 100%;">
                            <a class="alex-bt destaque verde-minimo" href="#" onclick="entrar()">Entrar</a>
                            <!--a class="alex-bt" href="#" onclick="document.formulario.reset()">Limpar</a-->
                        </div>
                        <a class="alex-bt destaque verde-minimo" href="/area-restrita/cadastre-se">Cadastre-se</a>
                        <a class="alex-bt" href="/area-restrita/esqueci-senha">Esqueci a senha</a>
                    </td>
                </tr>
            </table>
        </center>
    </form>
</div>

<?php
$this->placeholder('ConteudoEsquerda')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/sobre-nos/_menu.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
?>