<div class="CONTEINER">
    <div class="titulo" style="background-image: url('/temas/default/default/icones/search.png');">Sobre nós</div>
    <div class="painel MENU-LISTA">
        <ul><li><a href="/sobre-nos/quem-somos">Quem Somos</a></li>
            <li><a href="/sobre-nos/conheca-o-projeto">CONHEÇA o Projeto</a></li>
            <!--li><a href="/sobre-nos/faca-sua-doacao">Faça sua DOAÇÃO !</a></li-->
            <li><a href="/sobre-nos/como-ajudar">Como AJUDAR ?</a></li>
            <li><hr/></li>
            <li><a href="/sobre-nos/perguntas-frequentes">Perguntas Frequentes</a></li>
            <li><a href="/sobre-nos/politicas-e-termos">Políticas e Termos</a></li>
            <li><a href="/sobre-nos/recomendamos">Recomendamos</a></li>
        </ul>
    </div>
</div>
<div class="CONTEINER">
    <a class="titulo tituloSozinho" style="background-image: url('/temas/default/default/icones/comment.png');" href="/contato">Contato</a>
</div>