<?php $this->placeholder('Head')->captureStart() ?>
<title><?php echo DFL_NOME ?> - Sobre nós - CONHEÇA o Projeto !</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<?php $this->placeholder('Head')->captureEnd() ?>

<div class="CONTEINER">
    <div class="TEXTO">
        <div class="topico">OBJETIDO</div>
        <div class="p">
            O objetivo é organizar e consolidar dados que possam gerar informações resumidas e de fácil acesso para envolver e conscientizar os cidadãos sobre a vida pública e a qualidade do trabalho prestado pelos políticos brasileiros.
        </div>
        
        <div class="topico">ACESSO</div>
        <div class="p">
            Para democratizar o acesso ao projeto, ele será colocado na internet em forma de site e futuramente poderão ser desenvolvidos aplicativos para plataformas móveis. Com isso, a sociedade passará a contar com uma plataforma disponível para qualquer pessoa, com acesso a internet, onde será possível encontrar informações organizadas, consolidadas e centralizadas sobre a vida pública dos políticos brasileiros.
        </div>
        
        <div class="topico">INFORMAÇÕES</div>
        <div class="p">
            Todas as informações geradas serão baseadas em dados fornecidos por órgãos públicos e pela colaboração da sociedade dentro da plataforma.
        </div>
        <div class="p">
            Com os dados gerados pelo TSE, será possível registrar no sistema todas as pessoas que já tenham participado das eleições juntamente com suas candidaturas e declarações de patrimônios. Os veículos de comunicação poderão registrar notícias na linha do tempo de cada pessoa, o que formará um histórico de sua vida pública consultável pelos eleitores.
        </div>
        <div class="p">
            Já com os dados fornecidos pela Câmara e Senado será possível registrar todos os gastos e projetos dos políticos que foram eleitos e exercem seu mandato.
        </div>
        <div class="p">
            Os usuários cadastrados poderão publicar matérias na linha do tempo dos políticos e partidos formando, ao longo do tempo, um histórico dos pontos mais relevantes do seu trabalho, o que facilitará com que os eleitores “lembrem” das coisas boas e ruins que os candidatos tenham feito pela sociedade, e isso qualificará o seu voto.
        </div>
        <div class="p">
            Além dos prós e contras dos trabalhos dos candidatos, o eleitor poderá consultar seu histórico de candidaturas e analisar o seus gráficos de “Evolução Patrimonial”, “Consumo de Recursos Públicos”, “Aprovação Popular” e “Representação Popular”, o que dará ainda mais informações aos eleitores sobre seus possíveis candidatos.
        </div>
        <div class="p">
            Para envolver e conscientizar ainda mais os cidadãos sobre as decisões que afetam o seu dia a dia, não só na época das eleições, os usuários também poderão votar os projetos apresentados no congresso gerando um gráfico com a “Opinião Popular”, sobre o assunto. Este gráfico será enviado para os políticos relacionados deixando clara a vontade da população. Cruzando dados sobre a votação popular e a votação dos políticos, será gerado um gráfico que mostrará o quanto cada político representa a sociedade e o seu custo.
        </div>
    </div>
</div>

<?php $this->placeholder('ConteudoSocialize')->captureStart() ?>
<div class="MINIATURA">
    <div class="fb-like" data-href="<?php echo DFL_URL . '/sobre-nos/conheca-o-projeto' ?>" data-send="false" data-layout="box_count" data-show-faces="false" data-action="like"></div><br/>
    <div class="g-plusone" data-href="<?php echo DFL_URL . '/sobre-nos/conheca-o-projeto' ?>" data-size="tall" ></div><br/>
    <a class="twitter-share-button" href="https://twitter.com/share" data-url="<?php echo DFL_URL . '/sobre-nos/conheca-o-projeto' ?>" data-lang="en" data-text="Conheca o PROJETO ! (<?php echo DFL_URL ?>)" data-dnt="true" data-count="vertical"></a><br/>
</div>
<?php
$this->placeholder('ConteudoSocialize')->captureEnd();
$this->placeholder('ConteudoEsquerda')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/sobre-nos/_menu.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/_projeto.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/_noticias.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
?>