<?php $this->placeholder('Head')->captureStart() ?>
<title><?php echo DFL_NOME ?> - Sobre nós - Perguntas Frequentes</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<?php $this->placeholder('Head')->captureEnd() ?>

<div class="CONTEINER">
    <div class="TEXTO">
        <div class="topico">DE ONDE SÃO TIRADAS ESTAS INFORMAÇÕES ?</div>
        <div class="p">
            Todas as informações sobre os políticos foram extraídas de arquivos públicos fornecidos por órgãos como o TSE e Câmara do Deputados. No entanto também existem informações geradas pelo sistema e inseridas pelos usuários cadastrados no site, tais como o gráfico da evolução patrimonial e as notícias sobre os partidos e políticos, respectivamente.
        </div>
        
        <div class="topico">POR QUE DEVO ME CADASTRAR ?</div>
        <div class="p">
            Somente usuários cadastrados poderão votar os projetos, adicionar notícias, fazer comentários e utilizar diversos outros recursos do site.
        </div>
        
        <div class="topico">COMO ME CADASTRAR ?</div>
        <div class="p">
            Para se cadastrar você deve utilizar a autenticação do Facebook ou do Google+. Os botões ficarão destacados na parte superior das páginas do site.
        </div>
        
        <div class="topico">CADÊ O CADASTRO TRADICIONAL POR E-MAIL ?</div>
        <div class="p">
            Para dificultar que uma pessoa se cadastre mais de uma vez, com diferentes e-mails, somente será possível se cadastrar por autenticação social. Com cada usuário tendo apenas uma conta os resultados das estatísticas serão mais precisos, alem de facilitar o processo de remoção/bloqueio de usuários mal intencionados.
        </div>
        
        <div class="topico">COMO POSSO CONTRIBUIR COM O PROJETO ?</div>
        <div class="p">
            <a href="/sobre-nos/como-ajudar">Clique aqui</a> para conhecer todas as opções para quem quer nos ajudar.
        </div>
    </div>
</div>

<?php $this->placeholder('ConteudoSocialize')->captureStart() ?>
<div class="MINIATURA">
    <div class="fb-like" data-href="<?php echo DFL_URL . '/sobre-nos/perguntas-frequentes' ?>" data-send="false" data-layout="box_count" data-show-faces="false" data-action="like"></div><br/>
    <div class="g-plusone" data-href="<?php echo DFL_URL . '/sobre-nos/perguntas-frequentes' ?>" data-size="tall" ></div><br/>
    <a class="twitter-share-button" href="https://twitter.com/share" data-url="<?php echo DFL_URL . '/sobre-nos/perguntas-frequentes' ?>" data-lang="en" data-text="Perguntas Frequentes (<?php echo DFL_URL ?>)" data-dnt="true" data-count="vertical"></a><br/>
</div>
<?php
$this->placeholder('ConteudoSocialize')->captureEnd();
$this->placeholder('ConteudoEsquerda')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/sobre-nos/_menu.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/_projeto.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/_noticias.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
?>