<?php $this->placeholder('Head')->captureStart() ?>
<title><?php echo DFL_NOME ?> - Sobre nós - Políticas e Termos</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<?php $this->placeholder('Head')->captureEnd() ?>


<div class="CONTEINER">
    <div class="titulo">Política de Privacidade</div>
    <div class="TEXTO">
        <div class="p" style="text-indent: 0; padding-top: 20px">
            Antes de qualquer coisa, queremos deixar claro que esta Política está sujeita a
            alterações. Sendo assim recomendamos sua consulta regularmente. O objetivo desta é
            tornar transparente o modo como utilizaremos os dados coletados. Sinta-se a vontade para
            entrar em contato caso tenha algum questionamento.
        </div>
        <div class="topico">1. SOBRE A COLETA</div>
        <div class="p">
            ... em contrução.
        </div>
        <div class="topico">2. SOBRE A UTILIZAÇÃO</div>
        <div class="p">
            ... em contrução.
        </div>
        <div class="topico">3. SOBRE O CONTEÚDO GERADO</div>
        <div class="p">
            ... em contrução.
        </div>
        <div class="topico">4. SOBRE A RESPONSABILIDADE DO USUÁRIO</div>
        <div class="p">
            ... em contrução.
        </div>
    </div>
</div>

<div class="CONTEINER">
    <div class="titulo">Termos de Uso</div>
    <div class="TEXTO">
        <div class="p" style="text-indent: 0; padding-top: 20px">
            Antes de qualquer coisa, queremos deixar claro que esta Política está sujeita a
            alterações. Sendo assim recomendamos sua consulta regularmente. O objetivo desta é
            tornar transparente o modo como utilizaremos os dados coletados. Sinta-se a vontade para
            entrar em contato caso tenha algum questionamento.
        </div>
        <div class="topico">1. SOBRE A RELAÇÃO</div>
        <div class="p">
            ... em contrução.
        </div>
        <div class="topico">2. SOBRE A ACEITAÇÃO DOS TERMOS</div>
        <div class="p">
            ... em contrução.
        </div>
        <div class="topico">3. SOBRE A UTILIZAÇÃO DO SERVIÇO</div>
        <div class="p">
            ... em contrução.
        </div>
        <div class="topico">4. SOBRE A SEGURANÇA DAS INFORMAÇÕES PESSOAIS</div>
        <div class="p">
            ... em contrução.
        </div>
        <div class="topico">5. SOBRE OS DIREITOS DE PROPRIEDADE</div>
        <div class="p">
            ... em contrução.
        </div>
        <div class="topico">6. SOBRE A EXCLUSÃO DE GARANTIAS</div>
        <div class="p">
            ... em contrução.
        </div>
        <div class="topico">7. SOBRE A LIMITAÇÃO DE RESPONSABILIDADE</div>
        <div class="p">
            ... em contrução.
        </div>
        <div class="topico">8. SOBRE A ALTERAÇÃO DOS TERMOS</div>
        <div class="p">
            ... em contrução.
        </div>
        
        <div class="topico"><a name="sobre-o-cadastro">SOBRE O CADASTRO</a></div>
        <div class="p">
            ... em contrução.
        </div>
        
        <div class="topico"><a name="sobre-as-noticias">SOBRE AS NOTÍCIAS</a></div>
        <div class="p">
            Queremos que as notícias sejam adicionadas por qualquer pessoa bem intencionada, mas
            também precisamos ter controle sobre o recurso para que o mesmo não seja aproveitado por
            pessoas mal intencionadas.
        </div>
        <div class="p">
            Inicialmente todo usuário terá o direito de registrar as notícias sobre as pessoas e partidos
            que quiser dos sites que preferir desde que as notícias sejam adicionadas corretamente.
            Manteremos uma política rigorosa quanto a cadastros indevidos e o usuário poderá perder o
            direito de postar notícias, dependendo a gravidade do "problema". O usuário perderá tal
            direito nos seguintes casos:
        </div>
        <div class="p">
            <ul><li><b>-</b> Não colocar a "DATA DE PUBLICAÇÃO" original da notícia.</li>
                <li><b>-</b> Não colocar o "TÍTULO" original da notícia.</li>
                <li><b>-</b> Não colocar o "RESUMO" original da notícia. (*)</li>
                <li><b>-</b> Não colocar o "LINK" original da página da notícia.</li>
                <li><b>-</b> Colocar um "LINK DE IMAGEM" para uma imagem que não está na página da notícia. (*)</li>
                <li><b>-</b> Relacionar uma "PESSOA" que não foi citada no texto da notícia.</li>
                <li><b>-</b> Relacionar um "PARTIDO" que não foi citado no texto da notícia.</li>
            </ul>
        </div>
        <div class="p">
            (*) O "RESUMO" e o "LINK DA IMAGEM" deverão ser deixados em branco caso a notícia não
            possua ou caso o usuário não os encontre.
        </div>
        <div class="p">
            Inicialmente, todos os domínios terão o direito de ter seus links registrados no site
            por qualquer pessoa que tenha interesse de fazê-lo, mas também haverá punições para os
            domínios que tiverem notícias indevidas cadastradas no site. O domínio poderá perder o 
            direito de ter seus links divulgados nos seguintes casos: 
        </div>
        <div class="p">
            <ul><li><b>-</b> Caso veícule notícias que ferem a ética profissional do jornalismo.</li>
            </ul>
        </div>
        
        <div class="topico"><a name="sobre-os-projetos">SOBRE OS PROJETOS</a></div>
        <div class="p">
            ... em contrução.
        </div>
    </div>
</div>

<?php $this->placeholder('ConteudoSocialize')->captureStart() ?>
<div class="MINIATURA">
    <div class="fb-like" data-href="<?php echo DFL_URL . '/sobre-nos/politicas-e-termos' ?>" data-send="false" data-layout="box_count" data-show-faces="false" data-action="like"></div><br/>
    <div class="g-plusone" data-href="<?php echo DFL_URL . '/sobre-nos/politicas-e-termos' ?>" data-size="tall" ></div><br/>
    <a class="twitter-share-button" href="https://twitter.com/share" data-url="<?php echo DFL_URL . '/sobre-nos/politicas-e-termos' ?>" data-lang="en" data-text="Políticas e Termos (<?php echo DFL_URL ?>)" data-dnt="true" data-count="vertical"></a><br/>
</div>
<?php
$this->placeholder('ConteudoSocialize')->captureEnd();
$this->placeholder('ConteudoEsquerda')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/sobre-nos/_menu.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/_projeto.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/_noticias.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
?>