<div class="CONTEINER">
    <a href="/admin" class="titulo" style="background-image: url('/temas/default/default/icones/process.png');">Administração</a>
    <div class="painel MENU-LISTA">
        <ul><li><a href="/admin">Contatenar Pessoas</a></li>
            <li><a href="/admin/relacionar-pessoas">Relacionar Pessoas</a></li>
            <li><a href="/admin">Relacionar Partidos</a></li>
        </ul>
    </div>
</div>