<?php $this->placeholder('Head')->captureStart() ?>
<title><?php echo DFL_NOME ?> - Ranking - Partidos</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<script type="text/javascript" language="javascript" src="/scripts/alex/campo.js"></script>
<script type="text/javascript" language="javascript">
    function marcarFiltro(obj){
        if(obj.name == 'palavra_chave' && obj.value.length > 0 && obj.value != 'palavra-chave...'){
            marcaCampoOk(obj);
            return;
        }
        desmarcaCampo(obj);
    }
    function formSubmit(){
        link = '/ranking/partidos';
        palavra_chave = document.getElementById('palavra_chave');
        if(palavra_chave.value.length > 2 && palavra_chave.value != 'palavra-chave...'){
            link += '/palavra-chave/' + palavra_chave.value;
        }
        vaiPara(link);
    }
</script>
<?php $this->placeholder('Head')->captureEnd() ?>

<?php
if ($this->Lista['pagina']['qtd-itens'] > 0) {
    echo '<div class="RESULTADO" id="RESULTADO">';
    include APPLICATION_PATH . '/modules/default/views/scripts/ranking/ajax-paginacao-partidos.phtml';
    echo '</div>';
} else {
    echo '<div class="CONTEINER">';
    echo '<div class="RESULTADO">';
        echo '<div class="mensagem"><i>NENHUM PARTIDO FOI ENCONTRADO</i></div>';
    echo '</div>';
    echo '</div>';
}
?>

<script type="text/javascript" language="javascript">
    var jQPaginaStatus = 0;
    var jQPaginaAtual = <?php echo $this->Lista['pagina']['atual'] ?>;
    var jQPaginaFinal = <?php echo $this->Lista['pagina']['fim'] ?>;
    
    $(window).bind("scroll", function(){
        page = $('#CONTEUDO').height() + 200;
        if(($(window).scrollTop() + $(window).height() + 500) > page){
            if(jQPaginaStatus == 0 && jQPaginaAtual < jQPaginaFinal){
                jQPaginaStatus = 1;
                $.post('/ranking/ajax-paginacao-partidos/id/0', {
                    'pagina': ++jQPaginaAtual
                }, function(data){
                    jQPaginaStatus = 0;
                    document.getElementById('RESULTADO').innerHTML += data.toString();
                }, 'html');
            }
        }
    });
</script>

<?php
$this->placeholder('ConteudoEsquerda')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/sobre-nos/_menu.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
?>