<?php
foreach ($this->Lista['resultado'] as $obj) {
    echo '<div class="MINIATURA">';
        echo '<a class="foto" href="/partidos/' . $obj['partido_url'] . '" style="' . (($obj['partido_flags'][4]==1)?('background-image: url(\'/uploads/partidos/' . $obj['partido_id'] . '/foto.png\');'):('')) . '"></a>';
        echo '<div class="texto">';
            echo '<div class="nome">' . $obj['partido_sigla'] . ', ' . $obj['partido_numero'] . '</div>';
            echo '<div class="descricao">' . $obj['partido_nome'] . '</div>';
        echo '</div>';
    echo '</div>';
}
?>