<?php $this->placeholder('Head')->captureStart() ?>
<title>Candidaturas - <?php echo $this->obj['partido_nome'] . ' - Partidos - ' . DFL_NOME ?></title>
<meta name="keywords" content="<?php echo $this->obj['partido_sigla'] . ', ' . $this->obj['partido_nome'] ?>" />
<meta name="description" content="<?php echo $this->obj['partido_nome'] ?>" />
<?php $this->placeholder('Head')->captureEnd() ?>

<div class="CONTEINER">
    <div class="TEXTO">
        <div class="topico">Página...</div>
        <div class="p">
            ... em contrução.
        </div>
    </div>
</div>

<?php
$this->placeholder('ConteudoEsquerda')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/partidos/_menu.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/_projeto.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/_noticias.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/sobre-nos/_menu.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
?>