<?php $this->placeholder('Head')->captureStart() ?>
<title>Notícias - <?php echo $this->obj['partido_nome'] . ' - Partidos - ' . DFL_NOME ?></title>
<meta name="keywords" content="<?php echo $this->obj['partido_sigla'] . ', ' . $this->obj['partido_nome'] ?>" />
<meta name="description" content="<?php echo $this->obj['partido_nome'] ?>" />
<script type="text/javascript" language="javascript" src="/scripts/alex/campo.js"></script>
<script type="text/javascript" language="javascript">
    function marcarFiltro(obj){
        if(obj.name == 'palavra_chave'){
            if(obj.value.length > 0 && obj.value != 'palavra-chave...'){
                marcaCampoOk(obj);
                return;
            }
        }else{
            if(obj.value != 0){
                marcaCampoOk(obj);
                return;
            }
        }
        desmarcaCampo(obj);
    }
    function marcarFiltroAll(){
        marcarFiltro(document.getElementById('ordem'));
        marcarFiltro(document.getElementById('tema'));
        marcarFiltro(document.getElementById('veiculo'));
        marcarFiltro(document.getElementById('palavra_chave'));
    }
    function formSubmit(){
        link = '/partidos/<?php echo $this->obj['partido_id'] ?>/noticias';
        palavra_chave = document.getElementById('palavra_chave');
        if(palavra_chave.value.length > 2 && palavra_chave.value != 'palavra-chave...'){
            link += '/palavra-chave/' + palavra_chave.value;
        }
        if(document.getElementById('tema').value > 0){
            link += '/tema/' + document.getElementById('tema').value;
        }
        if(document.getElementById('veiculo').value > 0){
            link += '/veiculo/' + document.getElementById('veiculo').value;
        }
        if(document.getElementById('ordem').value == 'importancia'){
            link += '/ordem/importancia';
        }
        vaiPara(link);
    }
</script>
<style type="text/css">
.NOTICIA{
    width:362px;
}
</style>
<?php $this->placeholder('Head')->captureEnd() ?>

<div class="CONTEINER">
    <div class="FILTRO">
        <select id="ordem" class="item" onchange="marcarFiltro(this)" style="width:150px">
            <option value="0" class="label">Ordem</option>
            <option value="publicacao">Ordenar por Data de Publicação</option>
            <option <?php echo (isset($this->Lista['get']['ordem']) && $this->Lista['get']['ordem'] == 'importancia')?('selected="selected"'):('') ?> value="importancia">Ordenar por Importância</option>
        </select>
        <select id="tema" class="item" onchange="marcarFiltro(this)" style="width:150px;display:none">
            <option value="0" class="label">Temas</option>
            <?php
            foreach (Zend_Registry::get('db')->fetchAll('SELECT * FROM pro_tema ORDER BY tema_nome') as $value) {
                echo '<option value="' . $value['tema_id'] . '"';
                if(isset($this->Lista['get']['tema']) && $this->Lista['get']['tema'] == $value['tema_id']){
                    echo ' selected="selected"';
                }
                echo '>' . $value['tema_nome'] . '</option>';
            }
            ?>
        </select>
        <select id="veiculo" class="item" onchange="marcarFiltro(this)" style="width:150px">
            <option value="0" class="label">Veículos</option>
            <?php
            foreach (Zend_Registry::get('db')->fetchAll('SELECT * FROM not_veiculo ORDER BY veiculo_link') as $value) {
                if($value['veiculo_id'] > 0){
                    echo '<option value="' . $value['veiculo_id'] . '"';
                    if(isset($this->Lista['get']['veiculo']) && $this->Lista['get']['veiculo'] == $value['veiculo_id']){
                        echo ' selected="selected"';
                    }
                    echo '>' . $value['veiculo_nome'] . '</option>';
                }
            }
            ?>
        </select>
        <input type="hidden" id="palavra_chave_atual" value="<?php if(isset($this->Lista['get']['palavra-chave'])) echo $this->Lista['get']['palavra-chave'] ?>">
        <input type="text" id="palavra_chave" name="palavra_chave" class="item text" value="<?php echo (isset($this->Lista['get']['palavra-chave']) && $this->Lista['get']['palavra-chave'] != '') ? ($this->Lista['get']['palavra-chave']) : ('palavra-chave...'); ?>" lang="palavra-chave..." maxlength="100" onfocus="entrou(this)" onblur="saiu(this);marcarFiltro(this);" onkeyup="marcarFiltro(this)" title="Palavra-chave para a busca.">
        <a class="item alex-bt" onclick="formSubmit()" ><img class="icone" src="/temas/default/default/icones/search.png" title="Buscar" />Buscar</a>
        <a class="item alex-bt" href="/partidos/<?php echo $this->obj['partido_url'] ?>/noticias" style="background-image: url('/temas/default/default/icones/remove.png')" title="Reiniciar Busca" ></a>
    </div>
    
    <?php
    if ($this->Lista['pagina']['qtd-itens'] > 0) {
        echo '</div><div class="RESULTADO" id="RESULTADO">';
        include APPLICATION_PATH . '/modules/default/views/scripts/noticias/ajax-paginacao.phtml';
    } else {
        echo '<div class="RESULTADO"><div class="mensagem"><i>NENHUMA NOTÍCIA FOI ENCONTRADA</i></div></div>';
    }
    ?>
</div>

<script type="text/javascript" language="javascript">
    $('.ajaxNoticiasPartidoLigar').bind('mouseup', function(e){
        switch(e.which){
            case 1: //left Click
            case 2: //middle Click
            case 3: //right Click
                ajaxNoticiasPartidoLigar($(this).attr('noticia_id'), $(this).attr('partido_id'));
        }
    });
    var jQPaginaStatus = 0;
    var jQPaginaAtual = <?php echo $this->Lista['pagina']['atual'] ?>;
    var jQPaginaFinal = <?php echo $this->Lista['pagina']['fim'] ?>;
    
    $(window).bind("scroll", function(){
        page = $('#CONTEUDO').height() + 200;
        if(($(window).scrollTop() + $(window).height()) > page){
            if(jQPaginaStatus == 0 && jQPaginaAtual < jQPaginaFinal){
                jQPaginaStatus = 1;
                $.post('/noticias/ajax-paginacao/id/0', {
                    'pagina': ++jQPaginaAtual,
                    'partido': <?php echo $this->obj['partido_id'] ?>,
                    'ordem': '<?php echo (isset($this->Lista['get']['ordem']) && $this->Lista['get']['ordem'] == 'importancia')?('importancia'):('0') ?>',
                    'veiculo': <?php echo (isset($this->Lista['get']['veiculo']))?($this->Lista['get']['veiculo']):(0) ?>,
                    'tema': <?php echo (isset($this->Lista['get']['tema']))?($this->Lista['get']['tema']):(0) ?>,
                    'palavra-chave': document.getElementById('palavra_chave_atual').value
                }, function(data){
                    document.getElementById('RESULTADO').innerHTML += data.toString();
                    jQPaginaStatus = 0;
                }, 'html');
            }
        }
    });
    
    window.onload(marcarFiltroAll());
</script>

<?php
$this->placeholder('ConteudoEsquerda')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/partidos/_menu.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/_projeto.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/sobre-nos/_menu.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
?>