<?php $this->placeholder('Head')->captureStart() ?>
<title>Cargos - Brasil - <?php echo DFL_NOME ?></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<?php $this->placeholder('Head')->captureEnd() ?>

<div class="CONTEINER">
    <div class="TEXTO">
        <div class="topico">Página...</div>
        <div class="p">
            ... em contrução.
        </div>
    </div>
</div>

<?php $this->placeholder('ConteudoSocialize')->captureStart() ?>
<div class="MINIATURA">
    <a class="twitter-share-button" href="https://twitter.com/share" data-url="<?php echo DFL_URL . '/brasil/cargos' ?>" data-lang="en" data-text="Cargos Brasileiros" data-dnt="true" data-count="vertical"></a><br/>
    <div class="fb-like" data-href="<?php echo DFL_URL . '/brasil/cargos' ?>" data-send="false" data-layout="box_count" data-width="50" data-show-faces="false" data-action="like"></div><br/>
    <div class="g-plusone" data-size="tall" data-href="<?php echo DFL_URL . '/brasil/cargos' ?>"></div><br/>
</div>
<?php
$this->placeholder('ConteudoSocialize')->captureEnd();
$this->placeholder('ConteudoEsquerda')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/brasil/_menu.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/_projeto.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/_noticias.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/sobre-nos/_menu.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
$this->placeholder('ConteudoDireita')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/_direita.phtml';
$this->placeholder('ConteudoDireita')->captureEnd();
?>