<?php $this->placeholder('Head')->captureStart() ?>
<title>Leis - Brasil - <?php echo DFL_NOME ?></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<?php $this->placeholder('Head')->captureEnd() ?>

<div class="CONTEINER">
    <div class="titulo">Processo Legislativo</div>
    <div style="padding: 4px 4px 1px 4px">
        <iframe src="http://www.slideshare.net/slideshow/embed_code/27305628" width="726" height="585" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen></iframe>
    </div>
</div>

<div class="CONTEINER">
    <div class="titulo">Técnica Legislativa</div>
    <div style="padding: 4px 4px 1px 4px">
        <iframe src="http://www.slideshare.net/slideshow/embed_code/27307030" width="726" height="585" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen></iframe>
    </div>
</div>

<?php $this->placeholder('ConteudoSocialize')->captureStart() ?>
<div class="MINIATURA">
    <a class="twitter-share-button" href="https://twitter.com/share" data-url="<?php echo DFL_URL . '/brasil/leis' ?>" data-lang="en" data-text="Leis Brasileiras" data-dnt="true" data-count="vertical"></a><br/>
    <div class="fb-like" data-href="<?php echo DFL_URL . '/brasil/leis' ?>" data-send="false" data-layout="box_count" data-width="50" data-show-faces="false" data-action="like"></div><br/>
    <div class="g-plusone" data-size="tall" data-href="<?php echo DFL_URL . '/brasil/leis' ?>"></div><br/>
</div>
<?php
$this->placeholder('ConteudoSocialize')->captureEnd();
$this->placeholder('ConteudoEsquerda')->captureStart();
include APPLICATION_PATH . '/modules/default/views/scripts/brasil/_menu.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/_projeto.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/_noticias.phtml';
include APPLICATION_PATH . '/modules/default/views/scripts/sobre-nos/_menu.phtml';
$this->placeholder('ConteudoEsquerda')->captureEnd();
?>