<?php
$db = Zend_Registry::get('db');

$user = array();
if(Zend_Auth::getInstance()->hasIdentity()){
    foreach ($db->fetchAll('SELECT noticia_id, user_importancia_id FROM not_noticia_x_usuario WHERE noticia_id=' . $this->obj['noticia_id'] . ' && user_id=' . Zend_Auth::getInstance()->getIdentity()->user_id ) as $value) {
        $user[$value['noticia_id']] = $value['user_importancia_id'];
    }
}
?>

<div class="MINIATURA NOTICIA">
    <?php echo ($this->obj['noticia_imagem'] != '')?('<div class="imagem" title="' . $this->obj['noticia_titulo'] . '"><img src="' . $this->obj['noticia_imagem'] . '" /></div>'):('') ?>
    <div class="texto">
        <div class="nome"><a class="ajaxNoticiasLigar" target="_blank" noticia_id="<?php echo $this->obj['noticia_id'] ?>" href="<?php echo $this->obj['noticia_link'] ?>"><?php echo $this->obj['noticia_titulo'] ?></a></div>
        <div class="descricao"><a class="ajaxNoticiasLigar" target="_blank" noticia_id="<?php echo $this->obj['noticia_id'] ?>" href="<?php echo $this->obj['noticia_link'] ?>"><?php echo $this->obj['veiculo_link'] ?></a><?php echo (($this->obj['noticia_data'] != 0)?('<div class="topo">' . date('d/m/Y', $this->obj['noticia_data']) . '</div>'):('')) ?></div>
        <div class="descricao"><?php echo $this->obj['noticia_resumo'] ?></div>
    </div>
    <div class="opcoes">
        <a href="/noticias" title="Voltar Para as Notícias" style="background-image: url('/temas/default/default/icones/back.png')"></a>
        <div id="indiceNoticia<?php echo $this->obj['noticia_id'] ?>" style="float:right">
            <?php
            if(isset($user[$this->obj['noticia_id']])){
                $data = array('star_blue', $user[$this->obj['noticia_id']]);
            }else{
                $data = array('star_green', round($this->obj['noticia_importancia_media']));
            }
            foreach (Default_Model_Lista_Importancia::get() as $value) {
                if($data[1] >= $value[0]){
                    echo '<a ' . (($data[1] == $value[0])?('class="ativo"'):('')) . ' onclick="ajaxNoticiasImportancia(' . $this->obj['noticia_id'] . ', ' . $value[0] . ')" title="' . $value[1] . '" style="background-image: url(\'/temas/default/default/icones/' . $data[0] . '.png\')"></a>';
                }else{
                    echo '<a onclick="ajaxNoticiasImportancia(' . $this->obj['noticia_id'] . ', ' . $value[0] . ')" title="' . $value[1] . '" style="background-image: url(\'/temas/default/default/icones/star_gray.png\')"></a>';
                }
            }
            ?>
        </div>
    </div>
</div>