<style>
    .divTable{
        display: table;
        width: 710px;
        margin: 0 0 -20px -1px;
    }
    .divTable .miniatura{
        display: table-cell;
        vertical-align: top;
        width: 200px;
    }
    .divTable .miniatura .MINIATURA{
        width: 200px;
        margin: 0;
    }
    .divTable .temas{
        text-align: left;
        display: table-cell;
        margin-bottom: 10px;
    }
    .divTable .temas label{
        display: inline-block;
        padding: 3px 5px 3px 0;
        margin: 1px;
        cursor: pointer;
        background: #f1f1f1;
    }
    .divTable .temas label:hover{
        background: #fafafa;
    }
    .divTable .form{
        display: table-cell;
        vertical-align: top;
    }
    .divTable .form table{
        margin: -1px 0 10px 0;
        width: 500px;
    }
    
    .ListaSelect{
        position:absolute;
        width:3px;
        height:3px;
        z-index:99999999;
        opacity: 0;
        visibility: hidden;
    }
    .ListaSelect .corpo{
        position:absolute;
        margin-top: 30px;
        background:#fff;
        padding: 4px;
        width:360px;
        border:1px solid #000;
        border-radius:5px;
        -webkit-border-radius:5px;
        -moz-border-radius:5px;
        box-shadow:0 0 10px #000;
        -webkit-box-shadow:0 0 10px #000;
        -moz-box-shadow:0 0 10px #000;
    }
    .ListaSelect .scroll{
        overflow-y: scroll;
        height: 250px;
    }
    .ListaSelect .corpo .item{
        display: table;
        width: 100%;
        cursor: pointer;
    }
    .ListaSelect .corpo .item:hover{
        background: #f1f1f1;
    }
    .ListaSelect .corpo .item .foto{
        display: table-cell;
        width: 48px;
    }
    .ListaSelect .corpo .item .foto .img{
        width: 50px;
        height: 50px;
        margin-right: -2px;
        background-image: url('/temas/default/default/imagens/miniatura.png');
        background-position: center center;
        background-repeat: no-repeat;
        background-size: 50px;
    }
    .ListaSelect .corpo .item .texto{
        display: table-cell;
        vertical-align: top;
        padding: 9px 8px 7px 8px;
        text-align: left;
        font-size:15px;
    }
    .ListaSelect .corpo .item .texto .nome{
        font-size:11px;
        font-weight: bold;
    }
    
    .CTRLV{
        font-style:italic;
        color:#ccc;
    }
</style>

<center>
    <div class="divTable">
        <div class="temas">
            <div class="form" id="TABLE_DESTINO"></div>
            <h3 style="margin: -6px 0 5px 2px">Selecione os temas mais fortes nesta notícia?</h3>
            <?php
                foreach (Zend_Registry::get('db')->fetchAll('SELECT * FROM pro_tema ORDER BY tema_nome') as $value) {
                    echo '<label><input type="checkbox" name="noticia_temas" value="' . $value['tema_id'] . '" style="vertical-align: top" /><b style="display: inline-block; padding: 2px 0 0 2px;">' . $value['tema_nome'] . '</b></label>';
                }
                echo '<label><input type="checkbox" name="noticia_temas" value="0" style="vertical-align: top" /><b style="display: inline-block; padding: 2px 0 0 2px;">Outros</b></label>';
            ?>
        </div>
        <div class="miniatura">
            <div class="MINIATURA NOTICIA">
                <div class="imagem">
                    <?php
                    if(count($this->data['imagens']) > 0){
                        echo '<img src="' . $this->data['imagens'][(count($this->data['imagens'])-1)][2] . '" />';
                    }
                    ?>
                </div>
                <div class="texto">
                    <div class="nome"><a><?php echo substr($this->data['titulo'], 0, 50) . '...' ?></a></div>
                    <div class="descricao"><?php echo substr($this->data['descricao'], 0, 100) . '...' ?></div>
                </div>
            </div>
            <a class="alex-bt verde-minimo" style="width: 170px; margin-top: 10px;" onclick="salvar();">Salvar</a>
        </div>
    </div>
</center>

<input type="hidden" name="noticia_data" value="<?php echo $this->data['data'] ?>" />
<input type="hidden" name="noticia_link" value="<?php echo $this->data['link'] ?>" />
<input type="hidden" name="noticia_dominio" value="<?php echo $this->data['dominio'] ?>" />
<input type="hidden" name="noticia_titulo" value="<?php echo $this->data['titulo'] ?>" />
<input type="hidden" name="noticia_descricao" value="<?php echo $this->data['descricao'] ?>" />
<input type="hidden" name="noticia_palavra_chave" value="<?php echo $this->data['palavra-chave'] ?>" />
<input type="hidden" name="noticia_imagem" value="<?php echo (count($this->data['imagens'])>0)?($this->data['imagens'][(count($this->data['imagens'])-1)][2]):('') ?>" />
