<?php
$db = Zend_Registry::get('db');

$veiculos = array(0 => array('veiculo_nome' => '', 'veiculo_link' => ''));
foreach ($db->fetchAll('SELECT * FROM not_veiculo') as $value) {
    $veiculos[$value['veiculo_id']] = $value;
}

$temas = array(0 => array('tema_id' => '', 'tema_nome' => ''));
foreach ($db->fetchAll('SELECT * FROM pro_tema') as $value) {
    $temas[$value['tema_id']] = $value;
}

$user = array();
if(Zend_Auth::getInstance()->hasIdentity()){
    $tmp = array();
    foreach ($this->Lista['resultado'] as $obj) {
        $tmp[] = $obj['noticia_id'];
    }
    foreach ($db->fetchAll('SELECT noticia_id, user_importancia_id FROM not_noticia_x_usuario WHERE noticia_id IN (' . implode(', ', $tmp) . ') && user_id=' . Zend_Auth::getInstance()->getIdentity()->user_id ) as $value) {
        $user[$value['noticia_id']] = $value['user_importancia_id'];
    }
}
            
foreach ($this->Lista['resultado'] as $obj) {
    echo '<div class="MINIATURA NOTICIA">';
        if($obj['noticia_imagem'] != ''){
            echo '<div class="imagem" title="' . $obj['noticia_titulo'] . '"><img src="' . $obj['noticia_imagem'] . '" /></div>';
        }
        echo '<div class="texto">';
            echo '<div class="nome"><a class="ajaxNoticiasLigar" target="_blank" noticia_id="' . $obj['noticia_id'] . '" href="' . $obj['noticia_link'] . '">' . $obj['noticia_titulo'] . '</a></div>';
            echo '<div class="descricao"><a class="ajaxNoticiasLigar" target="_blank" noticia_id="' . $obj['noticia_id'] . '" href="' . $obj['noticia_link'] . '">' . $veiculos[$obj['noticia_veiculo_id']]['veiculo_link'] . '</a>' . (($obj['noticia_data'] != 0)?('<div class="topo">' . date('d/m/Y', $obj['noticia_data']) . '</div>'):('')) . '</div>';
            echo '<div class="descricao">' . $obj['noticia_resumo'] . '</div>';
        echo '</div>';
        echo '<div class="opcoes">';
            echo '<a href="/noticias/' . $obj['noticia_id'] . '" title="Detalhar" style="background-image: url(\'/temas/default/default/icones/zoom_in.png\')"></a>';
            echo '<div id="indiceNoticia' . $obj['noticia_id'] . '" style="float:right">';
                if(isset($user[$obj['noticia_id']])){
                    $data = array('star_blue', $user[$obj['noticia_id']]);
                }else{
                    $data = array('star_green', round($obj['noticia_importancia_media']));
                }
                foreach (Default_Model_Lista_Importancia::get() as $value) {
                    if($data[1] >= $value[0]){
                        echo '<a ' . (($data[1] == $value[0])?('class="ativo"'):('')) . ' onclick="ajaxNoticiasImportancia(' . $obj['noticia_id'] . ', ' . $value[0] . ')" title="' . $value[1] . '" style="background-image: url(\'/temas/default/default/icones/' . $data[0] . '.png\')"></a>';
                    }else{
                        echo '<a onclick="ajaxNoticiasImportancia(' . $obj['noticia_id'] . ', ' . $value[0] . ')" title="' . $value[1] . '" style="background-image: url(\'/temas/default/default/icones/star_gray.png\')"></a>';
                    }
                }
            echo '</div>';
        echo '</div>';
    echo '</div>';
}
?>